### ISSUE TITLE
DevOps: Make OS more specific

### ISSUE THREAD

**Issue by minthemiddle** [kamranahmedse/developer-roadmap#106]
`Unix` is not a system one w/could use in 2017 for web development. All popular systems in use are based on Linux. The two main stream are Debian based distros, such as Ubuntu Server, or Redhat based, particularly CentOS.

So you should replace `Unix` and `Linux` with `Ubuntu` and `CentOS`.

**Comment by Llbe** [comment]
Don't forget Debian itself ;-).

**Comment by minthemiddle** [comment]
Sure!

**Comment by thorerik** [comment]
Learning about Unix and the various flavours can most certaintly be helpful, FreeBSD and Illumos are both big players, knowing either or both of those is helpful if you move onto eg. POWER, which is a very much growing platform, where you'll encounter AIX. Just because you don't see it in the low end doesn't mean it doesn't exists, and that it isn't popular.

**Comment by saldanac** [comment]
add Debian :-)

**Comment by da-edra** [comment]
Hello, since this issue was still open and an OS list was deeply needed I created a **PR** to include some **Linux** distributions suitable for server use in production like RHEL, Debian, CentOS, etc. As well as two **Unix** based OS's (FreeBSD and macOS Server).

Please check it out [here](https://github.com/kamranahmedse/developer-roadmap/pull/328) and share your thoughts in the **PR** so we can improve it 😄

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
