### ISSUE TITLE
Add to DevOps: Email 

### ISSUE THREAD

**Issue by minthemiddle** [kamranahmedse/developer-roadmap#110]
E-Mail has been a core pillar of the web. You should at least know about ESPs, about SPF, DKIM and how to design HTML mails for the most important clients.

**Comment by damengilland** [comment]
I brought this up in #101 too.

I feel like email layout is more of a Front-End thing... but sending is more DevOps.  I wouldn't ever ask someone in DevOps to do design... best case that's going to get me something as ugly as Craigslist.

**Comment by skpy** [comment]
Whether you're sending your own email, of you're using something like Mailgun, or relying on an Exchange admin, or something in between, email is still a critical component of development and infrastructure.  You need to know when to email, and how to do it.  You need to understand that SMTP is not a real time protocol. You need to understand how to secure the transmissions (SSL/TLS SMTP on port 25 or 465 or 587, and which is which; as well as IMAPS POP3S).

Understanding whitelisting and greylisting, DomainKeys, SPF, DMARC, and more are all things that come into play.  You don't necessarily need to be a master of any of these, but you need to know about them and how to learn more quickly in order to respond to problems.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
