### ISSUE TITLE
Change color for completed items for a better visualization and prod of ourselves

### ISSUE THREAD

**Issue by marcosfreitas** [kamranahmedse/developer-roadmap#1114]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I was wondering if it could be a good enhancement because it makes much visual sense to me. Changing the color of the completed items for the right tonality of green means that it was checked.

![image](https://user-images.githubusercontent.com/1065688/152660292-d4b66f07-ffed-4fe7-9968-76df9943b0a9.png)

**Comment by Steindvart** [comment]
# My opinion
Hi! This looks cool, I agree with you. And I will add one more reason - we don't have different within `done` and `I wouldn't recommend` nodes.

### For example:
![image](https://user-images.githubusercontent.com/53004350/152667209-9cc03d54-11ce-4f68-a31f-16417af80d18.png)

## Style
The style of the `done` element, I think, would be better if:
- Color: `#70cc2f`
- Text: without `line-through`. Because this prevents you from reading those blocks that you have already passed (to repeat the material, for example)

### For example:
![image](https://user-images.githubusercontent.com/53004350/152667431-732ae1a9-c9fc-410a-a584-9448710512f8.png)

**Comment by marcosfreitas** [comment]
Awesome @Steindvart, I agree. On my suggestion, I just left @kamranahmedse to pick the right color :)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
