### ISSUE TITLE
Full stack path

### ISSUE THREAD

**Issue by olivif** [kamranahmedse/developer-roadmap#127]
Should there be a full stack path as well? Which pretty much involves both front-end and back-end but maybe also some specific full stack topics on how to debug across the stack, etc.

**Comment by savinger** [comment]
I feel like having both frontend and backend covers this... can you suggest some full stack topics?

**Comment by damengilland** [comment]
We've got back-end and front-end... the concept of "full stack" is really dated, in my opinion.  Everything now is complex enough to warrant specialization.  And the concept of a "full stack engineer" usually means they can dabble, but aren't great at either.  Usually. (=

**Comment by garrettw** [comment]
I couldn't agree more. Unfortunately there are still lots of job listings out there looking for full-stack devs; they're probably companies who either can't afford or don't think they need specialists.

**Comment by damengilland** [comment]
> I couldn't agree more. Unfortunately there are still lots of job listings out there looking for full-stack devs; they're probably companies who either can't afford or don't think they need specialists.

As experts, let's not pander to people we know are wrong. (=

**Comment by joshlewis** [comment]
I'm in agreement with @olivif, Full Stack isn't represented properly, and I feel it ought to be. This project claims to be a "roadmap to becoming a web developer", not a "roadmap to becoming a specialist web developer at a mid-size or large company". So you're missing some things.

Not every company needs specialists. Especially smaller startups. 

For instance, I work at a company with two full-time developers and an additional designer/developer combination role. We don't need more than that at the moment. We're all very efficient, but we have to be generalists because that's what our work calls for. It would slow us down massively if we had to say "Oh, no, I can't do that. That's front-end. Give that to the other guy." If his plate is full, it's my work, and I get it done, and I do it well. No excuses.

The last company I was at, I was the first developer hired, and I had to do every role, including working on business execution strategies, product strategy, etc.

Furthermore, I do a lot of contract work on the side to make extra money, and I'm working on starting a side business. All of those things require me to do _everything_, perhaps minus design, but sometimes even that, just to get things done and functional for a client on a budget.

The idea of specialization only works if you already know you plan to work for a mid-size or large company with teams of a dozen or more developers working on the same product. There are plenty of those out there, but let's not pretend that's the entire marketplace, or even the vast majority. 

So if you want to reflect the breadth of the marketplace, don't pretend that specialists are the only way to go these days. That's simply untrue.

**Comment by mcMickJuice** [comment]
Let's not stray away from why this issue was opened: do we need a full stack path.

IMO no we don't, we have both backend and frontend paths that details the technologies therein.  We can always include a section in the README, something like a FAQ, where we can mention what a "fullstack developer" is and why it's important to be competent in each stack.

**Comment by joshlewis** [comment]
@mcMickJuice That'll do. Thank you. I just can't let the concept that full stack is outdated or somehow lesser stand. It's not true, and we don't need more developers entering the workforce with that mentality.

**Comment by mcMickJuice** [comment]
For sure man. I 100% agree.

**Comment by vapurrmaid** [comment]
@mcMickJuice 's idea of including a quick definition in the README is a great idea and IMO closes this issue

**Comment by mcMickJuice** [comment]
I opened an issue this morning that I think could address this:

https://github.com/kamranahmedse/developer-roadmap/issues/316

**Comment by darkvn79** [comment]
Lol,  they're click

**Comment by nliz77** [comment]
Thx

**Comment by kamranahmedse** [comment]
Thanks guys. This is being worked upon and will be done after the 2020 release 🙏
