### ISSUE TITLE
Add Path for UX Design

### ISSUE THREAD

**Issue by damengilland** [kamranahmedse/developer-roadmap#136]
While this isn't a development role, I wanted to open a ticket to encourage people to talk about this.

This was a "getting to done" checklist from an agency I worked at in the past... may not be useful for all projects, but important that we all acknowledge that getting a site built / launched / supported / improved / maintained does take more than just developers.

* General Web Project Overview - Google Sheets || https://docs.google.com/spreadsheets/d/1rGSHT2kZQCahDqoQkryLJ1b3rEq_uVLEX2Qe10RCxB8

**Comment by damengilland** [comment]
Probably a dupe of https://github.com/kamranahmedse/developer-roadmap/issues/33

**Comment by togiberlin** [comment]
Well, it's pretty straightforward. My suggestion:

**UI ROADMAP (VISUAL)**
1. Learn Adobe XD or Sketch, download some UI kits and play with them
2. Get familiar with Adobe Photoshop, do a deep course, learn shortcuts (!)
3. Get familiar with Adobe Illustrator, do a deep course, learn shortcuts (!)
4. Know the difference between Flat Design and Skeuomorphic, and it's advantages / disadvantages
5. When is an app beautiful? a) symmetry b) color harmony c) composition
6. Read the Google Material Design guideline
7. Read the Apple iOS Human Interface guideline
8. Own an Android or iOS device to get a feel what a modern app should look like
9. Search and bookmark UI design pages (e.g. uimovement.com) , get inspiration a.k.a. "steal" designs
10. Pick an example app and redesign it. Upload rough concept on Behance.net
11. Build a portfolio 5-6 redesign concepts

**UX ROADMAP (PSYCHOLOGY)**
1. Read book "Designing for Behavior Change" by Stephen Wendel (!!!)
2. Read book "Hooked" by Nir Eyal
3. Read book "Evil By Design" by Chris Nodder
4. Read book "Universal Principles of Design" by Lidwell, Holden, Butler
5. Read book "100 Things Every Designer Needs to Know About People" by Susan Weinschenk
6. Read book "Don't make me think" by Steve Krug
7. Optional readings: "Nudge" by C. Sunstein and R. Thaler; "Thinking Fast & Slow" by Kahnemann; "Influence" by Cialdini; "Predictably Irrational" by Dan Ariely
8. Get into the habit of thinking in user flows aka user stories. Know how to create user stories, search templates on the net
9. Go to http://www.goodui.org/ and familiarize with those patterns
10. Learn about testing methods, e.g. A/B testing
11. Send links of your UI models to test users and evaluate via e.g. http://attrakdiff.de/index-en.html
12. Get into the habit of justifying your UX proposals always with solid numbers and statistics

**Comment by NonameSLdev** [comment]
Microcopy could also be added :)

**Comment by foodtooth** [comment]
I don't know how to response to the comment above. I actually want to have that kind of contents to be referenced from repo.

**Comment by togiberlin** [comment]
@foodtooth @NonameSLdev 
I'm currently working on it.
Here is a draft: https://github.com/togiberlin/ui-ux-designer-roadmap

It's not finished, though. UI path seems fine, but the UX path has a lot of buzzwords, that need explaining. I envision some sort of UX crash course

**Comment by kamranahmedse** [comment]
Thanks for reporting but this is strictly for the development.
