### ISSUE TITLE
Add Path for Product Manager

### ISSUE THREAD

**Issue by damengilland** [kamranahmedse/developer-roadmap#138]
While this isn't a development role, I wanted to open a ticket to encourage people to talk about this.

This was a "getting to done" checklist from an agency I worked at in the past... may not be useful for all projects, but important that we all acknowledge that getting a site built / launched / supported / improved / maintained does take more than just developers.

* General Web Project Overview - Google Sheets || https://docs.google.com/spreadsheets/d/1rGSHT2kZQCahDqoQkryLJ1b3rEq_uVLEX2Qe10RCxB8

**Comment by damengilland** [comment]
You can probably lump Business Analyst in here too.. Tech Strategist... similar roles with a subset of knowledge.

**Comment by luchillo17** [comment]
True, it's not a development role.

Though it is indeed related to the development process, in universities, the pensum for engineers (including software engineers) include the social and administrative aspects, because an engineer is expected to be able to lead and comunicate with it's team and with different aspects of the development process that doesn't directly relate to it, like UX designers.

However the repo's name is `developer-roadmap` instead of `software-engineer-roadmap`, so not sure if such paths or branches really should go into this roadmap.

**Comment by luchillo17** [comment]
Btw such a huge process in that spreadsheet, in my company i'm in charge of everything, from architecture design and planning to Dev-ops work (very common in small companies or startups).

**Comment by damengilland** [comment]
Think of building a house, right?  I'm sure years and years ago... our grandfathers built their entire house with their own two hands... plumbing, electrical, drywall, windows, floors... right?

And while you may be able to find one person who can do those things... if you want to build for enterprise, you typically need a team -- there's simply more work than can be done by one person in the desired timeframe.

I've been in the spot where I had to wear a lot of hats... I don't think it's sustainable.  For a startup especially... you're a strategist, UX designer, visual designer, architect, dev, QA, DevOps, accountant... and the guy who manages the company email server and unclogs the toilet.

Can you do it in the short term?  Maybe... but should we gear people for that?  If we want high quality... if we want things to get better faster... we should encourage them to specialize in various areas so they can get great at those specific things.

There's just no reasonable way for someone to be great and keep up to date with DevOps and UX Design and Mobile Dev best practices all at once...  You can get to be OK at a bunch of things, but the modern economy lends itself to freelance work -- why not just call in a team of focused experts to do the job?

I like the original scope of this project... I also think there's value in expanding the scope.  Been three weeks since any updates to the files were made... so it's fun to just talk with other experts too... ha!  I started updating some of the Balsamiq files on my own... trying to work through a bunch of the issues people brought up here... it's been fun.  Will post them when I get a bit more work done.

**Comment by luchillo17** [comment]
Also reading your second comment if we keep doing so this will become a software company organization map instead, because soon all people in such roles will want to add their path to the graph, like UX designers, QA Testers, accountants... the list goes on and on.

Aaaaand then it comes the long response when i'm right in the middle of writing this one.

@damengilland I agree with you, if it were still 2000-2005 when web development was relative easy or under control compared to now, but with current innovation speed in development, software and tool proliferation, specialization should be the rule.

You know, i was originally hired to develop a hybrid mobile app, never finished, all the time some client want's some new feature, but since that's not all the time they started to put me in charge of other projects in the meantime.

Results i'm good enough that they decide to put the other dev to take care of the mobile project (yeah when the hard part that was starting, structuring the app, planning the architecture, and the freaking build pipeline was already done), and now i'm the one to start every new project, think they really believe the `Full stack developer` role actually exists... !ja.

Anyway i agree, as times goes by, and development subject expands in depth and complexity, new specialization roles will come.

**Comment by togiberlin** [comment]
Although not explicitly about Product Management, I feel that UX shares a lot in common. This could be interesting:

https://github.com/togiberlin/ui-ux-designer-roadmap
