### ISSUE TITLE
Turn technologies clickable to show some description

### ISSUE THREAD

**Issue by williamespindola** [kamranahmedse/developer-roadmap#140]
When I saw this roadmap I thought. Why I should chose this technologies or the other one? Perhaps if each box was clickable to show some informations about each technology this informations will help others to decide which to chose.

**Comment by luchillo17** [comment]
That represents a big change in the structure of the project, the current structure is based on generating graphs as images, to do what you request, making it interactive, it would mean to make not an image of such graph, but an actual application, in such case the github readme would be out because i see no way of making an app that can be embedded in the github markdown.

Suppose someone makes an app out of it to make interactive, where would it be hosted and who would pay for the maintenance fee?

Though i like the idea, i don't see the author putting the effort to make such a change in technology, it's more likely that he will just make room in another markdown file or file structure to deal with the comparison between alternatives on frameworks.

Actually that's a better alternative than an application, the effort needed to make such app and give it support while still being able to create, delete or move nodes is not worth it, after all the project is supposed to be a roadmap.

Unless... you decide to take on such task and make a new repo that deals with that, if you ever do let me know, that would be an interesting side project.

**Comment by kamranahmedse** [comment]
> When I saw this roadmap I thought. Why I should chose this technologies or the other one?

It is all a matter of personal preference and research that you will put in. For me, I highlighted the ones that I think are more in demand comparatively in different colors. Plus as @luchillo17 said, it isn't in the scope of the project (won't be able to put this stuff in the image). It might be possible to make a [coggle](coggle.it) for it but that isn't relevant to this one.

Thank you for reporting though.
