### ISSUE TITLE
technologies choice

### ISSUE THREAD

**Issue by zpike** [kamranahmedse/developer-roadmap#142]
To beginners, I found I can not learn everything in the roadmaps. I just need to learn the appropriate ones. So can the roadmaps add some character about the some terms. For example, I just need to use Gradle or Maven in the Spring Project. If I know that Gradle is the better choice (just what i think), I don't need to focus on Maven.

**Comment by luchillo17** [comment]
Oh god please no, nooooo!! (pun intended)

That's not a really good idea, that will rise a lot of discussion about which is or is not the best `framework / lib / IDE ...` the list goes on.

There's not enough people that have dig down in both alternatives (even worse if you need to compare 3+ alternatives) to say which is better, almost everyone will say the one they currently use is better, because that's what they know, work for them and are comfortable with.

Maybe making another repo that links to this one where the community can focus on discussing which one is better but directly in this one is stretching the roadmap too much.

What do you think?

**Comment by garrettw** [comment]
That's true, it is a can of worms people usually don't want to open. But if a well-moderated discussion can be had that focuses, maybe, on a two-fold goal of selecting a tool that's good for beginners and one that's good for advanced users; those goals should help keep discussions more targeted.

**Comment by luchillo17** [comment]
That's the reason i suggest another repo focusing in such task, linking it to this one as related to path selection or something like that, also i think the owner of the repo will not want to get involved into such discussions so he will likely not update the roadmap accordingly.

**Comment by kamranahmedse** [comment]
Hi @zpike,

I agree with @luchillo17. This is not in the scope of the project to discuss the ups and downs of any technologies. 

> To beginners, I found I can not learn everything in the roadmaps. I just need to learn the appropriate ones

It already focuses on the bare minimum that one needs to learn and I left off a lot of things for the sake of brevity. Looking at the legends, it already highlights the tools and technologies that are more in demand these days in comparison to the tools of the similar nature. 

For example, if you look at the image below it doesn't say that you need to learn Jest, Mocha, Jasmine, Chai and should.js all of them; it says that you can pick any one of Jest, Mocha or Chai. And Mocha being yellow is the one that is more recommended.

![image](https://cloud.githubusercontent.com/assets/4921183/25321690/a27513f2-28c1-11e7-9233-a53e94c440c1.png)

Thank you.
