### ISSUE TITLE
Need for DevSecOps RoadMap

### ISSUE THREAD

**Issue by andran777** [kamranahmedse/developer-roadmap#1535]
**What is this issue about?**

> Requesting new Map for DevSecOps

**Enter the details about the issue here**

> I understand that there is already an open security issue for the backend path(https://github.com/kamranahmedse/developer-roadmap/issues/750) and DevOps Path(https://github.com/kamranahmedse/developer-roadmap/issues/1079).

Along side, it would be nice to have a separate roadmap for DevSecOps. So we could cover detailed topics on security.

Some reference links for DevSecOps, I found on internet
https://www.aquasec.com/cloud-native-academy/devsecops/devsecops/
https://www.aquasec.com/cloud-native-academy/devsecops/devsecops-tools/
https://www.tigera.io/learn/guides/devsecops/
https://www.atlassian.com/devops/devops-tools/devsecops-tools
https://mindmajix.com/security-devops-tools
https://www.beyondtrust.com/resources/glossary/devops-security

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. Unfortunately, I have to close it due to the lack of subject matter experts. However, I have put it in the backlog and we might revisit this later. Also, if you would like to contribute this roadmap, please have [a look at the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing/roadmap.md).
