### ISSUE TITLE
[Suggestion] PostgreSQL DBA

### ISSUE THREAD

**Issue by bharatkishoremaheshwari** [kamranahmedse/developer-roadmap#1547]
If possible do make it like the other roadmaps it will be more convinient.
Thank you.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
