### ISSUE TITLE
Cant see interactive roadmap with vpn+pi-hole

### ISSUE THREAD

**Issue by tera1oo4** [kamranahmedse/developer-roadmap#1645]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/47866013/187731865-ec83fc0b-8b44-4b99-b075-45df7da02abe.png">

**Comment by kamranahmedse** [comment]
@tera1oo4 did you try refreshing? Also, could you please share the console logs and your operating system and browser information?

**Comment by tera1oo4** [comment]
@kamranahmedse refreshing cant help. i use mac os 11.5.1 and chrome 103.0.5060.134. logs :
<img width="766" alt="image" src="https://user-images.githubusercontent.com/47866013/187733116-b9be63e0-6ec2-4e2f-848a-714c140f6db5.png">

**Comment by kamranahmedse** [comment]
@tera1oo4 thank you for sharing the information. I don't see any errors relevant to the website. It could be [because of the extensions](https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag) you have installed. Could you try in incognito maybe?

**Comment by kamranahmedse** [comment]
Closing it for no response, please re-open if the issue persists or anyone else has the same issue.
