### ISSUE TITLE
Add JSX to React

### ISSUE THREAD

**Issue by NonameSLdev** [kamranahmedse/developer-roadmap#166]
In the frontend roadmap, JSX should be added, with an arrow from React, as to learn react you need JSX.

**Comment by mapodev** [comment]
JSX is simple HTML syntax. So I guess you don't need to learn it, because you learned it in the first place.

**Comment by luchillo17** [comment]
@mapodev Is right, JSX is just a mix of JS and HTML with a few changes like `className` instead of `class` and a few other name collisions, though there's a few things React components does add to the mix of html properties, the editors with `IntelliJ` support are enough help as to just not consider JSX like a need to learn.

It's Just my opinion but adding JSX is overkill.

**Comment by NonameSLdev** [comment]
@mapodev @luchillo17 Sure thing, but we wouldn't want anyone to skip it when learning react, so I think it's a good addition. Also, while learning it is 5 minutes, it's also important for anyone using React.

**Comment by luchillo17** [comment]
Skipping it makes no sense, you get used to it while learning and developing React, you'll learn it whether you like it or not, maybe master it could be ignored but most of the time you don't need to master, just keep the docs open in the browser.

**Comment by kamranahmedse** [comment]
@NonameSLdev I agree with @mapodev and @luchillo17; you do it automatically while learning React. Adding it in a separate branch will only make the graph convoluted.
