### ISSUE TITLE
Go: add stdlib common packages

### ISSUE THREAD

**Issue by igorcafe** [kamranahmedse/developer-roadmap#1673]
Add packages like net, net/http, io, and so on

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
