### ISSUE TITLE
Add AJAX to front-end developement

### ISSUE THREAD

**Issue by NonameSLdev** [kamranahmedse/developer-roadmap#168]
AJAX needs to be added to front end development. Not much to add here :P

**Comment by luchillo17** [comment]
Really? AJAX? is that hard and wide subject to need a separate node from JS?

**Comment by kamranahmedse** [comment]
Hi @NonameSLdev, thank you for reporting but I agree with @luchillo17; I don't think ajax specifically needs a mention.

**Comment by NonameSLdev** [comment]
@kamranahmedse It's not a wide subject but it's pretty much necessary for frontend devs. Adding it wouldn't hurt and even help people who don't know about it. In order to become a front end developer you need to know ajax, so why not? That's the exact description of this project

**Comment by luchillo17** [comment]
@NonameSLdev Actually npm can be very complex with version control, and version compatibility, npm is a building block of today's development.

I don't see ajax as a subject to learn but rather a technique for http requests, if so we would have to add all other possible like XHR, Fetch, Web Sockets...

Maybe i'm being impartial since i think AJAX is too easy, but i think it doesn't need a mention.

**Comment by garrettw** [comment]
If I'm not mistaken, XHR *is* AJAX.

**Comment by NonameSLdev** [comment]
@luchillo17 But it is needed. For a lot of websites it's necessary, and without AJAX they can't operate. So why shouldn't it be added? Let's add it after the "Getting Deeper" section. Developers need to know it, thus making this roadmap incomplete. @kamranahmedse

**Comment by garrettw** [comment]
AJAX is a technique. It's true that many websites rely on asynchronous communication to accomplish their goals, but actual AJAX (which requires XML) is only one way of doing it. Async JS is a good skill to have, but these days you really don't have to know the vanilla JS way of doing it because there are many libraries that make it easier, some of which are in the roadmap already. I would be willing to bet that very few devs actually write async JS without relying on any library.

**Comment by luchillo17** [comment]
In the `Required for any path` section in top-left corner it says `HTTP/HTTPS and API's`, that section already should cover the Ajax technique, unless we want to cluster the graph to expand on that node, i think it shouldn't be included.

Though that's my opinion, if more people say it should than the people that say it should not...
