### ISSUE TITLE
[Suggestion] QA Engineer

### ISSUE THREAD

**Issue by snsk** [kamranahmedse/developer-roadmap#1708]
Headless Testing is a child element of Test Automation and should be placed before CI, because we believe that E2E testing embedded in CI is basically Headless. What do you think?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
