### ISSUE TITLE
Add Ui & Ux Roadmap

### ISSUE THREAD

**Issue by RaheemAmer** [kamranahmedse/developer-roadmap#1943]
## Suggestion

- https://bootcamp.uxdesign.cc/the-self-taught-ui-ux-designer-roadmap-in-2021-aa0f5b62cecb

## Screenshots

![image](https://user-images.githubusercontent.com/18606136/193384265-82064864-4c7d-44ec-a59d-87773d07bc1c.png)

![image](https://user-images.githubusercontent.com/18606136/193384244-033cf35f-edad-4598-a7c6-384369b93464.png)

**Comment by astitva0011** [comment]
they'll also ask you to add the Website's URL from where you've retrieved data for the particular issue.

**Comment by astitva0011** [comment]
> Do I just have to add the photo link ? [new to open source so please guide ]

they'll also gonna ask you to add the Website's URL from where you've retrieved data for the particular issue.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by marcusabaker35** [comment]
Really appreciated the in-depth UX discussion on the developer roadmap issue, so insightful! As someone learning user experience design, I’m curious how a ui ux designer balances developer priorities with user needs. I also reviewed this article: https://mobisoftinfotech.com/services/ui-ux-design What’s your process for deciding which UX items to highlight in a roadmap?
