### ISSUE TITLE
[Suggestion] Java Developer

### ISSUE THREAD

**Issue by mkrg-capco** [kamranahmedse/developer-roadmap#2004]
Imho putting testing at the end of the roadmap is wrong. It should be placed just after fundamentals. Maybe not all advanced topics like TDD, BDD, mutation testing etc, but basics like unit testing. Maybe split testing into basic of testing covering unit testing, mocking, maybe even TDD and advanced testing

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
