### ISSUE TITLE
[Suggestion] Software Architect

### ISSUE THREAD

**Issue by jerryephicacy** [kamranahmedse/developer-roadmap#2116]
Hi @kamranahmedse ,

1) Do you think Data structures / Algorithms would be important for this role?
2) In the Web/Mobile section, can we elaborate a little more like what tech stack would be required for mobile?
3) Can we also expand the Cloud Providers section and also include the related certifications?

Thank you.

**Comment by being-nitin** [comment]
could you assign this task to me

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
