### ISSUE TITLE
[Suggestion] Blockchain Developer

### ISSUE THREAD

**Issue by laverstation** [kamranahmedse/developer-roadmap#2511]
1. Add [Re - Entrancy Attack](https://www.certik.com/resources/blog/3K7ZUAKpOr1GW75J2i0VHh-what-is-a-reentracy-attack) 

2. Add CTF on Blockchain like [Ethernaut](https://ethernaut.openzeppelin.com/), [Damn Vulnerability Defi](https://www.damnvulnerabledefi.xyz/) and [Capture The Ether](https://capturetheether.com/)

3. Add Smart Contract Audit like [Certik](https://www.certik.com/) and [hackenproof](https://hackenproof.com/) and contest like [Code4Rena](https://code4rena.com/) and [Immunefi](https://immunefi.com/)

**Comment by jebitok-dev** [comment]
I would like to work on the Blockchain Developer Roadmap

**Comment by jebitok-dev** [comment]
I would like to work on the Blockchain Developer Roadmap

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
