### ISSUE TITLE
[Suggestion] Software Architect

### ISSUE THREAD

**Issue by oscarlopezp** [kamranahmedse/developer-roadmap#2597]
As Security, I would include a skillset for Performance Engineering: 

This Skillset could include: SLAs, SLOs, SLIs + KPIs + Non-Functional requirements + CPT + automation + Performance Testing strategies or Types for the Backend and the Frontend among others

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
