### ISSUE TITLE
[Suggestion] Blockchain Developer

### ISSUE THREAD

**Issue by Arpish00** [kamranahmedse/developer-roadmap#2932]
Peer-to-peer distributed Storage Protocol or more likely IPFS was missing!

Hello, the blockchain Roadmap looks pretty much resourceful, But I saw that distributed storage wasn't mentioned as long as I noticed. Storage is quite expensive in blockchain, and developer should use P2P storage/file sharing protocol like IPFS, and other options as needed for the sake of decentralization.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
