### ISSUE TITLE
Mutation testing for asp.net

### ISSUE THREAD

**Issue by MikolajKorbanek** [kamranahmedse/developer-roadmap#2939]
Hi! 

I would like to help .net get an idea about mutation testing. I can create aa node about it with Stryker library suggestion with materials.

Let me know if you want me to add this.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
