### ISSUE TITLE
[Suggestion] Software Architect

### ISSUE THREAD

**Issue by rafaelstz** [kamranahmedse/developer-roadmap#2944]
It could have PHP inside the **programming language** node.

![Capture d’écran, le 2022-11-15 à 12 12 06](https://user-images.githubusercontent.com/610598/201983241-964833f9-9883-440f-8603-0f2921126b13.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
