### ISSUE TITLE
[Suggestion] QA Engineer

### ISSUE THREAD

**Issue by oaxjogi** [kamranahmedse/developer-roadmap#3036]
If you write down Selenium, Playwright and Cypress for Frontend tAutomated Testing I would suggest Sahi Pro from Tyto Software also, because it is for mobile, Web, desktop, (headleass or not, with docker or not) and it builds on business-driven test automation (near to BDD) - that is the key. We need to use business processes as root for our test cases as we do in BDD/ATDD/BDTA.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
