### ISSUE TITLE
[Suggestion] Node.js Developer

### ISSUE THREAD

**Issue by doougui** [kamranahmedse/developer-roadmap#3041]
The full guide link for the Express.js framework is redirecting to a 404 link. 

![image](https://user-images.githubusercontent.com/44846329/204793688-b90bbdff-687f-4c36-b3fe-234c4e5428e0.png)
![image](https://user-images.githubusercontent.com/44846329/204793844-70d4dd56-98c1-4302-9920-12b6050a9d02.png)

**Comment by 10xtarun** [comment]
Hi,
The tutorialspoint website has changed the main URL for Node-ExpressJS guide and removed "l" from last character in the URL and the new URL is [Node Express Guide](https://www.tutorialspoint.com/nodejs/nodejs_express_framework.htm)
Also, I think the appropriate guide for ExpressJS is this [link](https://www.tutorialspoint.com/expressjs/index.htm) , this is also by tutorialspoint.

@kamranahmedse Please assign me this issue so that I can fix this if you approve of above solution.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
