### ISSUE TITLE
[Suggestion] QA Engineer

### ISSUE THREAD

**Issue by dennisgrck** [kamranahmedse/developer-roadmap#3042]
Hello,

I would like to suggest including the tool **Testmo** under the "Mange your Testing" node, as it is the standard unified testing tool to manage all manual test cases, exploratory tests and automated testing in one system. It is also listed as one of the major tools in the [Guru99 listing](https://www.guru99.com/testing-tools.html) which is often used for reference here, among others. I suggest using the following text and reference links:

-----

Testmo

Testmo is a unified test management tool. Software testing teams use it to manage their manual test cases, exploratory test sessions and test automation. Teams can design test cases, start test runs and enter test results. Test sessions can be used to manage exploratory and usability tests. And automated test results can be submitted from test automation tools to track and report results.

Links / content:

Official website: https://www.testmo.com/
Testmo example projects and code repositories: https://github.com/testmoapp

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
