### ISSUE TITLE
[Suggestion] JavaScript Roadmap Primitive Types

### ISSUE THREAD

**Issue by MinutesView** [kamranahmedse/developer-roadmap#3043]
Please make the primitive type "Mark as Done" option separately for all these topics:- 
string
number
bigint
boolean
undefined
Symbol
null

As Symbol is an Intermediate Topic, not all users can complete this topic (Symbol) at once. To keep track of completion Primitive Types it would be easier to mark them as done individually.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
