### ISSUE TITLE
[Suggestion] Software Design and Architecture

### ISSUE THREAD

**Issue by camerongable** [kamranahmedse/developer-roadmap#3045]
Hi, just wondering when this roadmap will get interactive nodes?

**Comment by PeterPCW** [comment]
Is this fixed? I can click through on the nodes to get the individual topics. If not that I'm not sure what else you meant.

**Comment by camerongable** [comment]
The nodes are now clickable, although a lot of them do not have any additional content.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
