### ISSUE TITLE
Suggestion (PHP & Mobile application development & Desktop application development & Game development 

### ISSUE THREAD

**Issue by Sanuthabdulmumin02082001** [kamranahmedse/developer-roadmap#3061]
It would be fantastic to do a roadmap for PHP (it is one of the top languages)  mobile application development, desktop application development and game development

**Comment by iPoetDev** [comment]
I first used PHP 20 years ago, now I come back to it.

So I created my own custom PHP roadmap from their docs and from PHP books TOC of amazon.

Proof Of Concept/ WIP: https://roadmap.sh/r?id=65bd25950c54812283803899

https://github.com/kamranahmedse/developer-roadmap/issues/4214#issuecomment-1924669139

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
