### ISSUE TITLE
[Suggestion] Java Developer

### ISSUE THREAD

**Issue by OzzyTheGiant** [kamranahmedse/developer-roadmap#3066]
For frameworks, Spark is kind of in a weird place right now. Last I checked, this framework is in hiatus and its developer hasn't had time to update it even though there was mention of him trying to get back to it a few years ago. I would think this is is sort of a dead framework.

Instead, may I recommend the more active Javalin framework? It's basically a fork of Spark and is just as easy to learn (has Kotlin support too).

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
