### ISSUE TITLE
[Suggestion] ASP.NET Core Developer

### ISSUE THREAD

**Issue by chkchun** [kamranahmedse/developer-roadmap#3068]
Hi,

Is Prism framework in the ASP.NET Core Developer roadmap?
https://prismlibrary.com/

And Blazor Server, Blazor WebAssembly as well not in roadmap.

Thanks for getting ASP.NET Core in the roadmap. This really a great work.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
