### ISSUE TITLE
C# way should be appended

### ISSUE THREAD

**Issue by kovyfive** [kamranahmedse/developer-roadmap#307]
Package manager 

- Nuget

Testing 

- NUnit (yellow)
- Specflow (grey)
- XUnit (grey)
- FluentAssertions
- Moq (yellow with seperate arrow)

Framework

- ASP.Net MVC 5 (yellow)
- WCF (Yellow)
- Entity
 
Debugger/Profiler

- ReSharper

Dependency Injection
- Unity (yellow)
- MEF
- Ninject

**Comment by natiki** [comment]
Testing: Shouldly (https://github.com/shouldly/shouldly)

Mocking:

- NSubsitutue https://github.com/nsubstitute/nsubstitute
- Fake It Easy: https://fakeiteasy.github.io/
- https://github.com/moq/moq

Dependency Injection

- Castle Windsor

**Comment by mcMickJuice** [comment]
should there be any mention about .net core vs full .net? Also databases?

**Comment by obcilion** [comment]
C# is a great language, but do you guys know how much it's used for new/existing projects compared to Ruby, Python, PHP etc?

**Comment by mcMickJuice** [comment]
I absolutely believe it should be included.  Where I live (Minneapolis) .NET developers are in high demand and they're writing their code in C#.  I know it differs by region and I'm a little biased as I started off as a .NET developer but if I'm starting a new project, I am choosing .NET/C# over ruby and php for the tooling and language support alone.

Moreover C# is a more popular language than ruby, python and php and while it's market share has dipped a bit (which I think is due to node.js) .NET Core being cross platform and coming to full maturation will cause the language usage to go back up.

https://insights.stackoverflow.com/survey/2017#technology-programming-languages

**Comment by m-wilczynski** [comment]
## Dependency Injection

I wouldn't mark Unity as yellow, at least not alone.
I would place 3-4 major IoC frameworks: **Autofac, Castle.Windsor, Unity**.
MEF is a little different, it should be marked as 'cool to know'.

## Frameworks

Frameworks should not recommend WCF as it's currently on hold for port to .NET Core (and would scare people away, anyway).

Web frameworks: **ASP.NET MVC, ASP.NET Core, NancyFx, ASP.NET WebAPI**
ORMs: NHibernate, EntityFramework, Dapper, 

## Testing

XUnit should be 'yellow', as it is currently used in production for most of the projects by Microsoft themselves.
Also include mocking frameworks: **NSubstitute** and **Moq**. 

## Package managers

Package managers should have also **MyGet** and **Paket** marked as 'grey'.

## Market share

In Europe .NET + Java are dominant technologies in enterprise market (Python, Node.js and Go are on the rise though). I've seen a lot of adoption by startups too, mostly due to rise of .NET Core.
Current big sites using .NET that you probably know? StackOverflow is a great example.

**Comment by kamranahmedse** [comment]
Hey thanks for opening the issue but we are not intentionally expanding Java, Go or C# to keep it a little less messy
