### ISSUE TITLE
[Suggestion] Vue developer

### ISSUE THREAD

**Issue by kwarabei** [kamranahmedse/developer-roadmap#3075]
The [roadmap](https://roadmap.sh/vue) recommends to learn Vue CLI though it is in the maintenance mode now according to the [docs](https://cli.vuejs.org/#getting-started). I presume it would be more approprite to change the Vue CLI note to new two separate records pointing to [create-vue](https://github.com/vuejs/create-vue) and [Vite](https://vitejs.dev/) as they replace Vue CLI in combination.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
