### ISSUE TITLE
Night Mode[Suggestion] Computer Science

### ISSUE THREAD

**Issue by Prachet-Jain** [kamranahmedse/developer-roadmap#3102]
It would be helpful is you slightly adjust the font color or better add a night mode toggle. I use a third party forced dark mode and  no words are visible of the main content.
![Screenshot (13)](https://user-images.githubusercontent.com/63013668/207434390-f7453116-2513-49df-ad2f-5efad16e1a6a.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
