### ISSUE TITLE
[Suggestion] Flutter Developer Roadmap Shortcomings

### ISSUE THREAD

**Issue by Xazin** [kamranahmedse/developer-roadmap#3198]
Hey there, I'm a software engineer working primarily with Dart/Flutter.

I noticed some shortcomings of the Flutter roadmap, which concerns me due to the fact that it might impact the ability of a Flutter developer, and their chances of landing a job.

The first shortcoming is the part about State Management. It currently lists 3 choices, which are GetX, VelocityX, and Redux. Professionally GetX is not looked very well upon. It frightens me that the 3 most widespread, well-documented, and best state management packages are NOT on the list. Of course I am biased as well, but VelocityX and Redux can never beat Provider, Riverpod Provider, nor BLoC. And although I don't want to debate this, GetX should, in my opinion, not even be on the list. You don't learn Flutter when using GetX, you learn GetX.

Provider, if I remember correctly, is the package which is currently (officially) recommended by Flutter. Riverpod Provider is created by the same author.

Another shortcoming I noticed, was the lack of explaining eg. InheritedWidget, and working with layout (MediaQuery, LayoutBuilder, Constraints) - See example https://docs.flutter.dev/development/ui/layout/constraints.

Just my two cents, happy holidays.

**Comment by nathanielgreen** [comment]
It actually lists 6 choices but they're just placed above the state management block.
 
![image](https://user-images.githubusercontent.com/11984722/210824558-e338d60b-bfa9-4eca-8ef1-314661a1b329.png)

Although even in its current state it could do with some tweaks. It seems pointless to discern between bloc + flutter_bloc since you'll be using both anyway if you use bloc with Flutter.

I agree that the options should be changed and limited to the 3 most recommended state management solutions: provider, bloc, and riverpod with the 'Personal Recommendation' sticker, since they're the current solutions that are widely community backed.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. State management section has been updated to include Riverpod. 

Regarding your second point:

> Another shortcoming I noticed, was the lack of explaining eg. InheritedWidget, and working with layout (MediaQuery, LayoutBuilder, Constraints) - See example https://docs.flutter.dev/development/ui/layout/constraints.

Could you please explain and provide the nested bullet list of items that you think should be there and their position in the roadmap?
