### ISSUE TITLE
Python Developer

### ISSUE THREAD

**Issue by shroominic** [kamranahmedse/developer-roadmap#3208]
just a small change:

Django is currently only listed under synchronous frameworks but it can use booth.
If you using wsgi then you it is syncronous but you can also run it using asgi.
(Django Async Docs)[https://docs.djangoproject.com/en/4.1/topics/async/]

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
