### ISSUE TITLE
[Suggestion] Vue Developer

### ISSUE THREAD

**Issue by totobo47** [kamranahmedse/developer-roadmap#3227]
Vue cli is not the best choice now. The official doc says that it's better to use Vite instead of vue cli.

**Comment by Miqueas** [comment]
Yeah, the docs says Vue CLI is in maintenance mode, I indeed to remove it or something

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
