### ISSUE TITLE
Update the react docs url in the roadmap

### ISSUE THREAD

**Issue by NicolasFlorez130** [kamranahmedse/developer-roadmap#3229]
Short time ago the [new react docs](https://beta.reactjs.org/) was updated with all the information about the hooks and various utilities just talking about functional components, letting aside all about the class compononents, that makes the learning from docs way lesser confusing than learning from the older ones. I think is a good idea update the roadmap links with that ones.

**Comment by bensonarafat** [comment]
Hi @NicolasFlorez130 
The new react docs are not completed, which are still in the beta version. 
I don't think updating it just yet is a good idea

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
