### ISSUE TITLE
[Suggestion] Show 'Ongoing', isimilar to 'Done', 'Pending'

### ISSUE THREAD

**Issue by sanjarcode** [kamranahmedse/developer-roadmap#3247]
\<Node status="pending" />
![image](https://user-images.githubusercontent.com/48156230/210934943-3ba250bd-634f-4fcd-97ef-12f2987a8e34.png)

\<Node status="done" />
![image](https://user-images.githubusercontent.com/48156230/210934958-e248bead-cfb2-47ae-b975-1004e0730fa8.png)

Suggestion: \<Node status="ongoing" />

**Comment by Hat52** [comment]
I would like to work on this issue

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
