### ISSUE TITLE
[Suggestion] PHP developer

### ISSUE THREAD

**Issue by natainditama** [kamranahmedse/developer-roadmap#3270]
Hi @kamranahmedse 

I have a suggestion for roadmap. Could you please create a PHP language roadmap ?

Thanks

**Comment by arikov10** [comment]
https://phptherightway.com/

**Comment by iPoetDev** [comment]
https://github.com/kamranahmedse/developer-roadmap/issues/4214#issuecomment-1924669139

I first used PHP 20 years ago, now I come back to it.

So I created my own custom PHP roadmap from their docs and from PHP books TOC of amazon.

Proof Of Concept/ WIP: https://roadmap.sh/r?id=65bd25950c54812283803899

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
