### ISSUE TITLE
Colouring

### ISSUE THREAD

**Issue by KittenzExe** [kamranahmedse/developer-roadmap#3363]
Hey there,
Not an issue but just one on the colour side of things.
1. Can there be an option to have light mode and dark mode between webpages?
2. The button colour difference between https://roadmap.sh/roadmaps and https://roadmap.sh seems a bit weird on the roadmaps page. To me, seems a bit out of place compared to the home page

**Comment by naqet** [comment]
I'll be more than happy to do the dark mode part. Just need the maintainer to assign me to the task.

**Comment by mehedihasan-git** [comment]
Everyone wants Dark Mode! Bring the dark mode, please. ✌🏼

**Comment by naqet** [comment]
I already made it. But it's waiting for approval:

https://github.com/kamranahmedse/developer-roadmap/pull/3376

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
