### ISSUE TITLE
Roadmap for Systems Programming

### ISSUE THREAD

**Issue by sumitbhanushali** [kamranahmedse/developer-roadmap#3383]
roadmap for learning systems programming like kernel, device drivers, compiler, programming language, Web server and OS development

Relevant books: 
[The Unix Programming Environment](http://www.amazon.com/gp/product/013937681X/ref=as_li_ss_tl?ie=UTF8&tag=mmamzn06-20&linkCode=as2&camp=217145&creative=399369&creativeASIN=013937681X) by Kernighan and Pike.
[The Linux Programming Interface: A Linux and UNIX System Programming Handbook](http://www.amazon.com/gp/product/1593272200/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1593272200&linkCode=as2&tag=mmamzn06-20) by Kerrisk.
[Unix Power Tools](http://www.amazon.com/gp/product/0596003307/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0596003307&linkCode=as2&tag=mmamzn06-20) by Powers, Peek, O'Reilly and Loukides.
[commandlinefu](http://www.commandlinefu.com/).
[Linux Server Hacks](http://www.amazon.com/gp/product/0596004613/ref=as_li_ss_tl?ie=UTF8&tag=mmamzn06-20&linkCode=as2&camp=217145&creative=399369&creativeASIN=0596004613).
[The single Unix specification](http://www.unix.org/online.html).
[Linux Kernel Development](http://www.amazon.com/gp/product/0672329468/ref=as_li_ss_tl?ie=UTF8&tag=mmamzn06-20&linkCode=as2&camp=217145&creative=399369&creativeASIN=0672329468) by Love.

**Comment by Octobug** [comment]
👍
My first thought when browsing the Computer Science roadmap.

**Comment by 0ctav0** [comment]
Is there any progress on making the roadmap? I want to see also about Windows kernel and programming on Windows API

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
