### ISSUE TITLE
[Suggestion] QA Engineer

### ISSUE THREAD

**Issue by jcruzgon** [kamranahmedse/developer-roadmap#3393]
Hey, nice idea the roadmap. I would move the Version Control (git) box next to the Automated Testing though, they should be hand in hand. BDD as a concept and cucumber as a tool also part of the automated testing.
Also a "modern" QA should have some knowledge of docker/Kubernetes and some cloud provider.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
