### ISSUE TITLE
[Suggestion] JavaScript Roadmap

### ISSUE THREAD

**Issue by n3ikha** [kamranahmedse/developer-roadmap#3399]
Hello Community, 

Firstly, will like to thank you! all for the awesome Roadmap.

Would be nice to have an added features with an input type of radio. Which can filter out based on the Expert level Topics (added the screenshot for reference: highlighted in yellow). 

Which can decluttered, with pleasant viewing and less intimating experience (information overload).

Thank you for your time and consideration.

![Screenshot for suggestion features](https://user-images.githubusercontent.com/119530635/216024618-b792c012-66a4-4c8d-acf3-a106db7247e2.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
