### ISSUE TITLE
[Suggestion] Frontend - Change "React Testing Library" to "Testing Library"

### ISSUE THREAD

**Issue by barryels** [kamranahmedse/developer-roadmap#3405]
Testing Library has many implementations beyond just React. In its current naming, the section might be skipped by some developers who are using frameworks other than React.js.

**Comment by mehedihasan-git** [comment]
I believe this should refer to [https://testing-library.com](https://testing-library.com/)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
