### ISSUE TITLE
[Suggestion] Machine learning / AI / openCV roadmap

### ISSUE THREAD

**Issue by sbbeez** [kamranahmedse/developer-roadmap#3407]
Today's an AI era. we need a roadmap to create AI/ML apps.

Can someone create roadmap for,
1. AI
2. ML
3. openCV or similar specially to manipulate images and get image/video output

**Comment by MrlolDev** [comment]
any update on this?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
