### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by Sadykhzadeh** [kamranahmedse/developer-roadmap#3411]
Hello there!

What about [SPA](https://en.m.wikipedia.org/wiki/Single-page_application)? From my perspective, add some information about this technology would be highly recommended for newbies!

More information may also be [here](https://developer.mozilla.org/en-US/docs/Glossary/SPA)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
