### ISSUE TITLE
[Suggestion] Computer Science

### ISSUE THREAD

**Issue by fcfl** [kamranahmedse/developer-roadmap#3424]
Great job! Looks absolutely awesome for some branches of CS but maybe it goes too deep into programming & dbs while completely overlooking many many branches such as logic and theory of computation, formal methods, UX (yes, it is a CS discipline in most comprehensive curricula), computer graphics, computer vision, virtual & augmented reality, digital signal processing, lambda-calculus & type theory, compilers, paradigms, robotics (which I know many graduations not to offer unfortunately) and others that I can't remember rn!

**Comment by kamranahmedse** [comment]
Thanks for the feedback @fcfl -- I agree with most of what you said but, we tried to keep it specific to the practical knowledge (not that the items you mentioned aren't practical, it's just that the mentioned items are comparatively more relevant in terms of what you might come across when working in the industry). Having said that, would you mind giving us a bullet list of topics that you think should be there and where in the roadmap?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
