### ISSUE TITLE
[Suggestion] Node.js Developer - invalid link

### ISSUE THREAD

**Issue by nmonastyrskyi** [kamranahmedse/developer-roadmap#3434]
ExpressJS invalid link

### Steps to reproduce:
1. Open ExpressJS popup
2. Click on the 3rd link

### AR
Link is invalid:
https://www.tutorialspoint.com/nodejs/nodejs_express_framework.html
### ER
Link is valid:
https://www.tutorialspoint.com/expressjs/index.htm

**Comment by amantank** [comment]
Can you please add the file path?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
