### ISSUE TITLE
[Suggestion] Cloud Developer / Architect

### ISSUE THREAD

**Issue by impondesk** [kamranahmedse/developer-roadmap#3447]
Appreciate If we can add cloud engineering, developer and architect paths added to this with AWS, Azure, GCP tc.
Appreciate your efforts.

**Comment by Kushan-Nilanga** [comment]
I am also interested in this—very minimal guidance and roadmaps on the Infrastructure and Cloud Architect roles.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
