### ISSUE TITLE
[Suggestion] Android Developer

### ISSUE THREAD

**Issue by imadulhassan** [kamranahmedse/developer-roadmap#3454]
It will be great if you add widget and architecture components section in roadmap . Here are few in the list below 
**Widgets** 
- Recylerview 
- BottomNavigationBar
- Viewpager 
- TabLayout
-  ListView
- Spinner 
- BottomSheetDialog 

**Component** 

- Viewmodels and Observers

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
