### ISSUE TITLE
[Suggestion] Quarkus in Java web frameworks

### ISSUE THREAD

**Issue by rajdip-b** [kamranahmedse/developer-roadmap#3468]
Quarkus is a relatively new java framework and should be present in the java roadmap under web frameworks.

**Comment by pkonopacki1** [comment]
Agree!

**Comment by marcelolemes** [comment]
Agreed!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
