### ISSUE TITLE
[Suggestion] Firebase/Firestore NoSQL Backend Developer

### ISSUE THREAD

**Issue by noh24** [kamranahmedse/developer-roadmap#3469]
FYI: This is my first suggestion so I don't know how helpful this is but here are just a few thoughts

Have you had any thoughts on adding Firestore as a NoSql? As you may already know, Firebase is a BaaS that offers two types of database services. Firestore is a document-based, NoSQL database. 

Here are some guides that I found very helpful. It is relatively short and only covers the bare basics but it's better than nothing. 

Intro to Firebase as BaaS and Firestore: https://www.learnhowtoprogram.com/react/react-with-nosql/introduction-to-baas-firebase-and-firestore

How to create Firebase Account and setup Firestore db in Node.js: https://www.learnhowtoprogram.com/react/react-with-nosql/setting-up-a-firebase-project-firestore-database-and-web-app

Lessons step by step to cover basic CRUD and the starter repo
https://github.com/epicodus-lessons/react-help-queue-starter-project
https://www.learnhowtoprogram.com/react/react-with-nosql/adding-firebase-to-react
https://www.learnhowtoprogram.com/react/react-with-nosql/adding-tickets-to-firestore
https://www.learnhowtoprogram.com/react/react-with-nosql/viewing-tickets-from-firestore
https://www.learnhowtoprogram.com/react/react-with-nosql/updating-and-deleting-tickets-in-firestore

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
