### ISSUE TITLE
[Suggestion] Computer Science

### ISSUE THREAD

**Issue by 183aryan** [kamranahmedse/developer-roadmap#3472]
I think one of the most important topic i.e., dynamic programming is missing from this roadmap. So, please add it.

And I would like to contribute in this topic. So what is the way to contribute. Please explain the steps.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
