### ISSUE TITLE
[Suggestion] React Developer

### ISSUE THREAD

**Issue by rafaelflorespereira** [kamranahmedse/developer-roadmap#3476]
react-query, as it is based on promises, should not be only beneath REST subcategory of API's. It also supports GraphQL

**Comment by rafaelflorespereira** [comment]
Should there be an independent subcategory from API calls or that would be sort of messy?
I just mentioned that that, because react-query beneath this could be misleading.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
