### ISSUE TITLE
HTML Email Developer Roadmap

### ISSUE THREAD

**Issue by Tendo44** [kamranahmedse/developer-roadmap#3484]
Please, create a clear cut roadmap to becoming A HTML Email Developer.

Thank you

**Comment by genericdude1998** [comment]
Great suggestion, I would argue it would be great to have a specific section just for emails like SMTP, spf, dkim, dmarc. We are having great difficulties with emails at my current company. It is a bit of obscure art tbh

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
