### ISSUE TITLE
[Suggestion] Node.js Developer

### ISSUE THREAD

**Issue by aeh1707** [kamranahmedse/developer-roadmap#3491]
The link that talks about the history of Node.js is missing from the official website, I suggest changing it.

![image](https://user-images.githubusercontent.com/95165255/221313937-b94937ab-4bbd-454e-aeae-4588f1f81084.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
