### ISSUE TITLE
[Suggestion] DevOps Roadmap

### ISSUE THREAD

**Issue by KrisTC** [kamranahmedse/developer-roadmap#3510]
You don't have source control or artefact management. Everyone basically uses git now, but not everyone would use public hosted services like github / bitbucket.

We also extensively use artifactory from jfrog for all our artifact management and is a key part of our developer  workflow.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
