### ISSUE TITLE
[Wrong Information] MFU-Cache is not correctly defined

### ISSUE THREAD

**Issue by TimJ0212** [kamranahmedse/developer-roadmap#3540]
Thanks for your work!

While reading the CS-Roadmap, I got confused with the Cache Algorithms. 

The MFU-Cache-Algorithm isn't defined by the removal of the "**least frequently used entry**".
Instead, it is the "**most recently used entry**" (source: [Wikipedia](https://en.wikipedia.org/wiki/Cache_replacement_policies#Most_recently_used_(MRU))

File: src/data/roadmaps/computer-science/content/104-common-algorithms/109-cache-algorithms/102-mfu-cache.md

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
