### ISSUE TITLE
[Suggestion] Javascript - Change "Chrome Dev Tools" to "Browser Dev Tools"

### ISSUE THREAD

**Issue by scheinercc** [kamranahmedse/developer-roadmap#3542]
Dev Tools have many implementations beyond just Chrome. In its current naming, the section might be skipped by some developers who are using browsers other than Chrome.
[117-javascript-chrome-dev-tools](https://github.com/kamranahmedse/developer-roadmap/tree/8f8e2f41d838ea577e6e28e12ef4b5ccb1091e82/src/roadmaps/javascript/content/117-javascript-chrome-dev-tools)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by scheinercc** [comment]
Thanks for all your work Kamran!
