### ISSUE TITLE
[Suggestion] REST API Roadmap

### ISSUE THREAD

**Issue by shota-nukumizu** [kamranahmedse/developer-roadmap#3548]
Please add roadmap.sh to REST API.

[Reason] In spite of GraphQL roadmap, roadmap.sh don't have REST API roadmap. Both are used in web development in public.

Useful topics are followed:

* [How to Use REST APIs – A Complete Beginner's Guide - freeCodeCamp](https://www.freecodecamp.org/news/how-to-use-rest-api/)
* [REST API Best Practices – REST Endpoint Design Examples - freeCodeCamp](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/)
* [10 Best Practices for Better RESTful API - Medium](https://medium.com/@mwaysolutions/10-best-practices-for-better-restful-api-cbe81b06f291)
* [REST API tutorial](https://www.restapitutorial.com/)
* [Top Resources for Learning and Designing REST APIs](https://www.crowdbotics.com/blog/top-resources-learn-and-design-rest-apis)
* [What is a REST API?](https://www.ibm.com/topics/rest-apis)
* [What is Rest API? Features, Principles, And Challenges - knowledgehuts](https://www.knowledgehut.com/blog/programming/rest-api)
* [Best practices for REST API design - Stack Overflow Blog](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
