### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by joparedesm** [kamranahmedse/developer-roadmap#3577]
Hi there,
I know it can be a bit difficult because of all the info, but since it has become such a big and well-known proyect... shouldn't it start being translated into other languages?

1. Not everyone knows English, especially beginners.
2. Despite knowing English, some people prefer to read in their native language.

**Comment by nina-alin** [comment]
Hi! Great suggestion! 

We could use i18n as it has an integration with astro: https://github.com/yassinedoghri/astro-i18next

**Comment by lucianodiisouza** [comment]
Im able to contribute for japanese and portuguese translations as needed!

**Comment by FlavioNevs** [comment]
Im able to contribute for pt-br as well

**Comment by gu-alves** [comment]
I would be happy to contribute to PT-BR too!

**Comment by Deguang** [comment]
I'd like to contribute to the Chinese translation of this project.

**Comment by littlemoji** [comment]
I can contribute for Chinese. After initializing i18n, please add a comment. I am looking forward to contributing for PT-BR too!

**Comment by littlemoji** [comment]
Have you encountered any problems with i18n? It seems this issue hasn't been updated in a while
I am also looking forward to contributing for PT-BR.

**Comment by skoenig** [comment]
It is generally a good idea to offer content in multiple languages. However, I'm not sure how much added value this would offer if the translations were limited to the original content of https://roadmap.sh. Do you think the directive for linked content should still be in English?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
