### ISSUE TITLE
[Typo] in Computer Science roadmap

### ISSUE THREAD

**Issue by Mahmoud-AbouDeghedy** [kamranahmedse/developer-roadmap#3582]
In "Common Runtimes" section, the example used for **exponential**  runtime runs in O(n) :
![image_2023-03-12_153034](https://user-images.githubusercontent.com/67663696/224547912-7bdd7192-209e-4196-9ff4-5be5b54e180e.png)
You can replace it with the recursive calculation of Fibonacci numbers:
![image_2023-03-12_153555](https://user-images.githubusercontent.com/67663696/224548198-2ebcfe3d-aa0a-4f4e-aa1e-c837ecfaea50.png)

**Comment by nina-alin** [comment]
Why would you replace it with the calculation of Fibonacci? I see two points here:

- The initial example is written in Python. Your example seems to be written in C++. I think most beginners in Computer Science (who are most likely to search for this roadmap) know Python. C++ is a more "advanced" language.
- What is the problem with the first example? It runs in O(n), like your Fibonacci algorithm. I think it is a nice example. Instead of replacing it, maybe we could just add it to the already existing algorithm.

**Comment by Mahmoud-AbouDeghedy** [comment]
1. It doesn't matter it it is written in C++, Python, or any other language.
2. A added the Fibonacci example because the first example runs in O(n) and the **recursive** Fibonacci example runs in O(2^n) time, but you can add any other O(2^n) example if you want.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
