### ISSUE TITLE
[Typo] in Computer Science roadmap 

### ISSUE THREAD

**Issue by Mahmoud-AbouDeghedy** [kamranahmedse/developer-roadmap#3583]
In "Common Runtimes" section, the example used for **factorial**runtime runs in O(n) :
![image](https://user-images.githubusercontent.com/67663696/224549392-4e2254c8-af5a-4033-afb0-1aecb0be96bc.png)
You can replace it with this C++ function:

```c++
void nFacRuntimeFunc(int n) {
  if(n==0)
    return;
  for(int i=0; i<n; i++) {
    nFacRuntimeFunc(n-1);
  }
}
```

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
