### ISSUE TITLE
[Suggestion] Frontend Developer - Accessibility 

### ISSUE THREAD

**Issue by geoffreycrofte** [kamranahmedse/developer-roadmap#3601]
Hello friends,

At the era of inclusivity and at this year 2023, I found sad that accessibility isn't a mandatory point in this roadmap.

Indeed, in Europe, the European Accessibility Act is adopted by most countries with the deadline of 2025.
In the US and Canada, it's mandatory since some years ago now. 

This isn't an optional step, it becomes more and more important everywhere, and even mandatory in some countries if you want to be employable. 

That's not a personal opinion, that's purely factual. At Foyer, my current employer, we are even thinking of accepting only trained people in accessibility from now on. 

As a professional and recruiter, I really recommend this to be marked as important in the path proposed. 

Thank you 😊

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by geoffreycrofte** [comment]
Hello,
No it's all right, I saw that accessibility has been added to the list.
Thanks!
