### ISSUE TITLE
[Suggestion] Adding boilderplates or projects for the skill based roadmaps

### ISSUE THREAD

**Issue by anhvupt** [kamranahmedse/developer-roadmap#3603]
Hello, 

I recently started using the skill-based roadmaps provided by this project and found them to be incredibly helpful for identifying areas where I need to improve and for guiding my learning of new skills. However, I think it would be even more useful if there were some boilerplates or sample projects available that could be used as a starting point for building out these skills.

For example, if I'm following the roadmap for learning React, it would be great to have a pre-built React app or some sample code that I can use as a reference when building my own projects. This would not only help me get started more quickly, but it would also provide a concrete example of how to apply the skills I'm learning.

I understand that everyone's learning journey is unique and that there is no one-size-fits-all solution, but having some boilerplates or sample projects available would be a great supplement to the existing roadmaps. It could also help to provide more context and motivation for learners who are just starting out.

Overall, I think this would be a valuable addition to the project and could help make the skill-based roadmaps even more useful for learners of all levels. 

Thank you for considering my suggestion!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
