### ISSUE TITLE
[Suggestion] Frontend Performance Best Practices - Minify JavaScript update link

### ISSUE THREAD

**Issue by edwinvanderven** [kamranahmedse/developer-roadmap#3609]
👋  Hi,

I noticed that one of the links on the minify JavaScript page is no longer working: https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/best-practices/frontend-performance/content/minify-your-javascript.md
- [Short read: How is HTTP/2 different? Should we still minify and concatenate?](https://scaleyourcode.com/blog/article/28)

----

As an alternative, the same organization does have a video on YouTube with the content available: https://www.youtube.com/watch?v=WUdKyzCLeG0

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
