### ISSUE TITLE
[Bug] Backend Developer - Cassandra isnt a column DB

### ISSUE THREAD

**Issue by zoomix** [kamranahmedse/developer-roadmap#3612]
Just a note. Cassandra is not a column DB. See 2.1 in this doc https://www.baeldung.com/cassandra-column-family-data-model

It's much closer to key-value store than a column db if you have to put a label on it. If you're allowed to create new subgroups, partitioned db, or even partitioned key-value db. Ideally Partitioned Row DB.

Sorry. I'm messing up your system and I know the label won't fit. But .. a column DB it is not.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by zoomix** [comment]
Hi!

Appreciate the effort and you've been doing a great job. 

This issue is however still relevant. Cassandra is a column-family database, as opposed to a column-oriented or row-oriented. It's a third kind. As per https://www.baeldung.com/cassandra-column-family-data-model.

```
...  is due to Cassandra’s ability to store and access column families separately, which results in a mistaken classification as column-oriented rather than column-family.
```

> 
> Let’s take an Employees table as an example:
>  ```
>   ID         Last    First   Age
>   1          Cooper  James   32
>   2          Bell    Lisa    57
>   3          Young   Joseph  45
> ```
> 
> A row-oriented database stores the above data as:
> 
> ```
> 1,Cooper,James,32;2,Bell,Lisa,57;3,Young,Joseph,45;
> ```
> 
> While a column-oriented database stores the data as:
> 
> ```
> 1,2,3;Cooper,Bell,Young;James,Lisa,Joseph;32,57,45;
> ```
> 
> Cassandra does **not store** its data like either a row-oriented or a column-oriented database.

**Comment by zoomix** [comment]
(i'm not allowed to reopen issues fwiw =)
