### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by rdylina** [kamranahmedse/developer-roadmap#3644]
pnpm should be the recommendation going forward.

**Comment by rdylina** [comment]
> All of them are good and none/all should be recommended as the one to go.
> 
> The issue is that it's marked differently. Given people don't read small texts, people think that another/dashy color = good. Personal recommendation of an unknown person posted on a website which doesn't seem to belong to a single person is confusing to say the least. At least name the person who recommended it and link their github/twitter/linkedin.

I disagree. At a minimum pnpm is quickly becoming the standard over using npm. Most of the time it's more a question of whether to use pnpm or yarn in most dev environments. 

As for the personal recommendation. It's the personal recommendation of the person who created the roadmap. Take a look at the repo owner if you're very curious. His name and link is also listed at the bottom of the page. @kamranahmedse

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
