### ISSUE TITLE
[Suggestion] Software Design and Architecture

### ISSUE THREAD

**Issue by LeinaGray** [kamranahmedse/developer-roadmap#3659]
Hi!

The road maps are difficult to read, 
so I want u to convert it into a mind map instead.

A mind map that only shows child branches when clicked. 

For example, parent branch Architectural Patterns should hide Domain-Driven Design, SOA, CQRS, etc. I'm overwhelmed by jargons. I don't understand them. I wanna see the abstracted overview first. Not the subparts. 

I'd really love the roadmap if it was built this way. Thank you!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
