### ISSUE TITLE
[Suggestion] Blockchain Developer

### ISSUE THREAD

**Issue by cryshado** [kamranahmedse/developer-roadmap#3669]
Hi! I would like to propose the creation of a `TVM-Based` blockchains group (like `EVM-Based` in the current version of [Blockchain Roadmap](https://roadmap.sh/blockchain)). Right now only one of the existing blockchain [TON (TONCOIN)](https://ton.org/) is represented in the roadmap. But we have a few more TVM-Based blockchains in our world: [Everscale](https://everscale.network/), [Venom](https://venom.foundation/) and [Gosh](https://gosh.sh/) – all of this use [`TON Virtual Machine`](https://ton-blockchain.github.io/docs/tvm.pdf) or are compatible with it.

**Comment by Mathew1327** [comment]
I'll take this

**Comment by cryshado** [comment]
@Mathew1327 Thank you! @ilyar – member of our community has created a PR #3671, which draws an example of what it might look like, and there are also texts for sections in md format. But there is no generation for the roadmap itself, we did not find a description or documentation of how to do this.

**Comment by pyAndr3w** [comment]
I will also add that The TON Blockchain stands for **The Open Network**, and the virtual machine (TVM) - **Telegram Open Network VM**.

So, it's a good idea to add other blockchains using the same virtual machine and create a separate group for them.

**Comment by cryshado** [comment]
@Mathew1327 any updates?

**Comment by cryshado** [comment]
@kamranahmedse Hi! Please advise what we can do to promote this issue and associated PR?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
