### ISSUE TITLE
[Suggestion] Updating the Android roadmap

### ISSUE THREAD

**Issue by dombroks** [kamranahmedse/developer-roadmap#3681]
Hi, the Android roadmap is a little bit outdated, there are things that should be already there like Background services and Broadcast recievers, and thing that are relatively new like Flow, Jetpack Compose, DataStore. Also, adding some architectural patterns like MVVM and MVI is a plus. Overall, I think the roadmap should be recreated. Thanks.

**Comment by Chetansbiradar** [comment]
@dombroks I agree that the Android roadmap should be recreated to be more interactive and include links to documentation and videos, similar to other roadmaps on the site.

**Comment by dombroks** [comment]
I might take charge of updating it if the responsible gave the permission.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
