### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by akellbl4** [kamranahmedse/developer-roadmap#3707]
Move Next.js into the first place instead of Remix.
Many reasons for doing it. Two main are Next.js is the first option that is recommended by the React docs and Next.js has more jobs on the market so it makes more sense to learn it.

**Comment by ahmarammar** [comment]
@akellbl4 I agree with you. For a beginner, I think Next.js is a more established framework than Remix. Remix is fast but from a beginner's point of view, Next.js should be in the first place.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
