### ISSUE TITLE
[Suggestion] React Roadmap 

### ISSUE THREAD

**Issue by devrahuls** [kamranahmedse/developer-roadmap#3728]
I think there is no need to use one more link for the exact same example. The link that I want to remove "Creating Custom Hooks", redirects the user to the old react documentation which is already listed in this md file as "Reusing Logic with Custom Hooks".

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
