### ISSUE TITLE
[Suggestion] Vue Developer

### ISSUE THREAD

**Issue by skirtles-code** [kamranahmedse/developer-roadmap#3741]
Some changes you might consider:

* `nextTick` is not part of the Composition API. I'd consider not including `nextTick()` at all, as it seems no more important than several other topics that aren't mentioned.
* Vue CLI has been replaced. `create-vue` is now used for scaffolding, which uses Vite. Vitest is a popular choice for unit testing.
* I would remove Vuepress and Gridsome and add VitePress instead.
* Vue Formulate was for Vue 2. It's now FormKit.
* VueUse is a really important part of the Vue ecosystem.
* The API Calls section seems a bit out of place. Several of the libraries listed there are orthogonal to using Vue. Some are very rarely used in practice.
* If props are seen as fundamental then I think custom events and slots are too. Arguably component `v-model` deserves a separate mention too. I would probably have scoped slots listed separately, as an advanced topic. If the Fundamentals section feels a bit crowded, I think Attribute Inheritance could be moved down to Advanced.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
