### ISSUE TITLE
[Suggestion] Blockchain Developer

### ISSUE THREAD

**Issue by AdrianScarlet** [kamranahmedse/developer-roadmap#3751]
The link to "[Consensus Mechanisms in Blockchain: A Beginner’s Guide](https://crypto.com/university/consensus-mechanisms-in-blockchain)" inside the CONSENSUS MECHANISMS  chapter within Blockchain Developer Roadmap is no longer available.

**Comment by AIpill** [comment]
Yes true I check it

**Comment by AIpill** [comment]
I will fix it

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
