### ISSUE TITLE
[Correct spelling of Wireframing] UX Design

### ISSUE THREAD

**Issue by coleoala** [kamranahmedse/developer-roadmap#3758]
Just noticed a typo 

![Screenshot 2023-04-04 at 10 46 14 AM](https://user-images.githubusercontent.com/42750429/229830130-ebc166c0-6a04-4c34-95ae-479ae7c069b6.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
