### ISSUE TITLE
Data Science Roadmaps

### ISSUE THREAD

**Issue by Tadiwr** [kamranahmedse/developer-roadmap#3778]
Hie my name is Tadiwa, I was kindly requesting if you could add a roadmap for data science fields like analysts and machine learning engineering. It would be really appreciated. Just let me know what you think.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
