### ISSUE TITLE
[NEW ROADMAP] Artificial Intelligence (AI)

### ISSUE THREAD

**Issue by JustJakeCalifornia** [kamranahmedse/developer-roadmap#3780]
Would love to see some kind of roadmap that fully covers AI w/ Machine Learning, Deep Learning, etc.

**Comment by baxtrax** [comment]
+1

**Comment by MrlolDev** [comment]
+1

**Comment by dewstend** [comment]
@ItsJustNico There should already be an AI roadmap here: https://roadmap.sh/ai-data-scientist

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
