### ISSUE TITLE
[Suggestion] Python Developer

### ISSUE THREAD

**Issue by Shashank127131** [kamranahmedse/developer-roadmap#3798]
Edit "Devops Roadmap" link to "Javascript Roadmap" as the link redirects to javascript developer roadmap.
<img width="1134" alt="Screenshot 2023-04-12 at 4 34 48 AM" src="https://user-images.githubusercontent.com/121549591/231307397-0e415f38-a957-4bd1-84b5-7ebb79d9b2d2.png">

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
