### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by Xunny-D** [kamranahmedse/developer-roadmap#3809]
Suggestion for a feature change: Add a bookmark feature to tag/mark a box or topic. Bookmarks could be used to set half-point goals or keep track of a topic that you want to revisit/prioritize for later.

**Comment by dikshant2406** [comment]
Looking for a same sort of suggestions in issues. This will be a great addition.
A button to add bookmarks on right of "mark of pending" might be great.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58582902/233801987-d15bad82-6719-4edd-ad9c-4c45140e3c0a.png">

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
