### ISSUE TITLE
[Suggestion] UX Design

### ISSUE THREAD

**Issue by noah-jansen** [kamranahmedse/developer-roadmap#3824]
"Wieframing" should be "Wireframing"

![Wieframing](https://user-images.githubusercontent.com/117166828/232441387-bfee31d2-c823-495d-8d78-6aa683024988.jpg)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
