### ISSUE TITLE
Goodies idea

### ISSUE THREAD

**Issue by robinportigliatti** [kamranahmedse/developer-roadmap#3840]
Hello,

I think it could be a good idea to sell poster of the roadmaps where you can scratch the tasks like scratch games.

Or just poster, it would be awesome too.

Robin,

**Comment by umairraza96** [comment]
Also stickers to put on our laptops :)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
