### ISSUE TITLE
[Feature] Linking cards together when you click done 

### ISSUE THREAD

**Issue by Eirfire** [kamranahmedse/developer-roadmap#3842]
For certain cards they are the same thing for example Javascript as a language is on multiple different roadmaps but when you click done on one roadmap it doesn't flow to another.

What would be nice is for this to be implemented then there is less duplication across roadmaps and that when one card is updated (clicked done ) that is syncs across all roadmaps

**Comment by BraxOBrian** [comment]
That would be great 👍

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
