### ISSUE TITLE
[Suggestion] Computer Science: add a specific section about disjoint-set

### ISSUE THREAD

**Issue by paoloconi96** [kamranahmedse/developer-roadmap#3843]
To fully understand Kruskal's algorithm and all the topics related to the minimum spanning tree I think it is quite important to know the teory behind the [disjoint-set](https://en.wikipedia.org/wiki/Disjoint-set_data_structure).

The topic is already covered undirectly in other lessons but I think that a specific section with specific resourses related to the topic would be really useful.

Thank you for your time and keep up with the great work. 🚀

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
