### ISSUE TITLE
[Suggestion] React Developer

### ISSUE THREAD

**Issue by JustLolo** [kamranahmedse/developer-roadmap#3845]
in https://roadmap.sh/react -> rendering -> Ref -> [Learn useRef in 11 Minutes - Web Dev Simplified](https://www.youtube.com/watch?v=t2ypzz6gJm0)

This video is misleading bc the examples it gives are pretty misleading If you are a beginner.

It shows more than one example that is only working bc useEffect is not rendering when `current` property of ref is changed.
You can see this in the last example the author provide, when ref is used as a prev value, if for any reason, anything else triggers a render, this example will not work as expected and the `previous` value will show the actual value.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
