### ISSUE TITLE
[Feature] Mention time taken for completion for each Roadmap

### ISSUE THREAD

**Issue by shriraj2k1o** [kamranahmedse/developer-roadmap#3846]
Mentioning the time taken to complete topics/ tasks/ milestones will motivate students further, and help them plan their studies.
The average time taken to complete a topic can be calculated on the basis of recommended material.
Others (from the community) can suggest directly how much time would they recommend to complete certain tasks/ topics.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
