### ISSUE TITLE
[Suggestion] Java Developer: jooq, mybatis, visualVM-like tools, java reactive stack

### ISSUE THREAD

**Issue by gneginskiy** [kamranahmedse/developer-roadmap#3861]
My suggestion is to consider adding JOOQ and MyBatis. Those are pretty popular frameworks.
also, tools like VisualVM/YourKitTools/Java Mission Control might be also worth adding.
Additionally, various options for reactive java stack may be also good fit for the roadmap, e.g. [something from this github](https://github.com/politrons/reactive)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
