### ISSUE TITLE
[Suggestion] add Data Engineer roadmap

### ISSUE THREAD

**Issue by gabriel-batistuta** [kamranahmedse/developer-roadmap#3864]
# add a Data Engineer roadmap

A data engineer is an IT worker whose primary job is to prepare data for analytical or operational uses. These software engineers are typically responsible for building data pipelines to bring together information from different source systems.

## referencies:

- https://www.techtarget.com/searchdatamanagement/definition/data-engineer

- https://github.com/adilkhash/Data-Engineering-HowTo

- https://github.com/igorbarinov/awesome-data-engineering

- https://medium.com/@darshilp/roadmap-for-data-engineering-2023-13f62f85d866

- https://github.com/ErdemOzgen/Data-Engineering-Roadmap

**Comment by sukurocking** [comment]
Adding reference to a similar request raised: https://github.com/kamranahmedse/developer-roadmap/issues/3719

**Comment by equinox98201** [comment]
Kindly add a data engineering roadmap for a newbie.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
