### ISSUE TITLE
[Suggestion] Request for feature to highlight specific resources in a node

### ISSUE THREAD

**Issue by Pravendra235** [kamranahmedse/developer-roadmap#3869]
It could be very useful to allow readers to highlight/mark some of the resources in a particular node. That would make it easy for us to figure out which resources were the most useful when visiting back.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
