### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by nivalt** [kamranahmedse/developer-roadmap#3870]
Download button in the "Beginner Version" download the wrong form of the "Detailed Version" not as expected.

Suggestion: 
* Download the page to pdf should be correlated to the page the user is viewing.
![Screenshot 2023-04-27 145938](https://user-images.githubusercontent.com/49100236/234855450-5e63e130-8cd7-4653-86d5-50075b2dd854.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
