### ISSUE TITLE
[Suggestion] Computer Science

### ISSUE THREAD

**Issue by denisfouchard** [kamranahmedse/developer-roadmap#3878]
Computer Science include fundamental computer science, and even a basic knowledge of theoretical computer science is big bonus. It would be interesting to add language theory, DFAs, context-free and Discrete clause grammar, as well propositional/first order logic (at least the basics). An introduction to markov chains for graph surfing as well would be relevant. 

Maybe also add dynamic programming and linear programming ? (as well as heuristics/meta-heuristics, genetic algorithms...)

Maybe we could add fundamentals of programming paradigms (OO, functional, imperative, ...)

I love your initiative and your work ! Thank you a lot for that ! 

(how about adding a math for CS or ML section ? I could help for that too if interested)

**Comment by adel3li** [comment]
I support this opinion especially for people who don't come from a computer science background.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
