### ISSUE TITLE
[Suggestion] JavaScript Roadmap

### ISSUE THREAD

**Issue by valentinopatane** [kamranahmedse/developer-roadmap#3884]
I would add a button to reset all boxes marked as done in a specific roadmap

Something like this:

![resetmarkasdone](https://user-images.githubusercontent.com/91293101/235933027-d9fe4e05-f8e8-4ccd-adf2-c43ce2c6479b.png)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
