### ISSUE TITLE
[Suggestion] C++ Developer

### ISSUE THREAD

**Issue by AngelYF** [kamranahmedse/developer-roadmap#3890]
It would be nice have this one.

**Comment by adel3li** [comment]
yeah surly we all need it.

**Comment by Polidoro-root** [comment]
I agree, I'm looking for a C reference for testing and this roadmap is the first thing that I though

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
