### ISSUE TITLE
[Suggestion] Computer Science

### ISSUE THREAD

**Issue by andreiaribas** [kamranahmedse/developer-roadmap#3895]
Create a beginner / simplified version of the Computer Science roadmap for people who just want to understand the most important basics / intermediate. The frontend roadmap has a beginner version, I suggest something like that.
Thanks

**Comment by adel3li** [comment]
I support this opinion specially for people who don't come from a computer science background.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
