### ISSUE TITLE
[Suggestion] Go Developer - Duplicate nodes of "Conditionals"

### ISSUE THREAD

**Issue by Octobug** [kamranahmedse/developer-roadmap#3900]
- Page: <https://roadmap.sh/golang>
- Section: `Learn the Basics`
  - `Conditionals`
  - `if, switch statements`

These two nodes are named differently, but they actually point to the same topic: [Conditional Statements (107-conditionals.md)](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/golang/content/100-go-basics/107-conditionals.md)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
