### ISSUE TITLE
[Suggestion] GraphQL

### ISSUE THREAD

**Issue by JulienMaring** [kamranahmedse/developer-roadmap#3914]
Can you please change the color?

**Comment by kamranahmedse** [comment]
Which color?

**Comment by JulienMaring** [comment]
It looks like this on my phone. I can't read it.
![Screenshot_20230512_192924_com brave browser](https://github.com/kamranahmedse/developer-roadmap/assets/74600129/330baf60-3fe8-4617-a084-9f2537f39f14)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
