### ISSUE TITLE
mark task as done

### ISSUE THREAD

**Issue by dle42573** [kamranahmedse/developer-roadmap#3917]
Should marking a task as done sync between different paths? For example if I mark something in frontend path as done and there is the exact same task in backend, should it be marked as done automatically as well? Can you consider implementing this? Thank you.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
