### ISSUE TITLE
[Suggestion] All Roadmaps — a glanceable 'Update Status' & a visually apparent path already traversed upon

### ISSUE THREAD

**Issue by Sidver-pod** [kamranahmedse/developer-roadmap#3939]
In '**Update Status**', I like the little green dot that indicates '**Done**' or even the little mustard-yellow dot that indicates '**In Progress**'. What I don't like is the grey-coloured box that forms with a strike across the topic name after marking it, say, 'Done'. Why? Because that colour interferes with the grey coloured boxes of "_I wouldn't recommend_". Instead, I suggest you add the same little green dot along with the word 'Done' on a white-coloured card, then let that card rest on top of the topic name itself. When a user hovers their mouse on top of the box, hide the card and reveal the topic name. It would feel more natural to glance at any point and know what is done or is in progress. Similar indications for other options of 'Update Status' can also be given.

Also, if, by any chance, there is a way to put in something like **footprints** or a colour-code on the path already traversed upon, it would be an immense visual treat!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
