### ISSUE TITLE
[Suggestion] System Design Thoughput definition

### ISSUE THREAD

**Issue by FranciscoPereira987** [kamranahmedse/developer-roadmap#3940]
Hello everyone, I believe there is an issue with this definition of *Throughput* that is presented on the roadmap:

- Throughput $\longrightarrow$ Throughput refers to the number of requests a system can handle at the same time.

Throughput doesn´t refer to the amount of requests *at the same time* but rather to the number of requests that a system can handle on a *unit* of time. 
Maybe im wrong, but I think requests don´t need to occur in parallel, as the definition presented in the roadmap implies.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
