### ISSUE TITLE
[Suggestion] Ability to add comments/notes

### ISSUE THREAD

**Issue by sevak995** [kamranahmedse/developer-roadmap#3945]
It will be very handy to have the ability to add comments/notes on each box, where we can note our custom resources to learn more!

**Comment by rubickecho** [comment]
yes, i also want it

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
