### ISSUE TITLE
[Bug] PostgreSQL DBA

### ISSUE THREAD

**Issue by BaikenM** [kamranahmedse/developer-roadmap#3950]
After choosing a node and scrolling down through its contents, two scroll bar knobs appear. Suggest showing an appropriate scroll bar depending on the current cursor focus.

**Comment by kamranahmedse** [comment]
Can you please share a screenshot/video?

**Comment by BaikenM** [comment]
Certainly! Here's a short clip.

https://github.com/kamranahmedse/developer-roadmap/assets/30524729/9da05b09-b844-461c-943d-f912add1b4d9

**Comment by mkhalid-s** [comment]
Could you share the browser details? 

_Checked it on Safari and Chrome. Works fine for me.
Safari: Version 16.5 (18615.2.9.11.4)
Chrome: Version 113.0.5672.126 (Official Build) (x86_64)_

**Comment by BaikenM** [comment]
I'm using Firefox: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) 
Gecko/20100101 
Firefox/113.0

**Comment by mkhalid-s** [comment]
ok. I see the point. The scroll/flex overlaps for "Relative container" and "Astro Island".

Maybe changing 
`fixed right-0 top-0 z-40 h-screen w-full overflow-y-auto bg-white p-4 sm:max-w-[600px] sm:p-6`
TO 
`fixed right-2 top-0 z-50 h-screen w-full overflow-y-auto bg-white p-4 sm:max-w-[600px] sm:p-6`
will give some Right spacing to the scroll that should not overlap with each other.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
