### ISSUE TITLE
[Suggestion] Cyber Security Expert

### ISSUE THREAD

**Issue by Akriti2304** [kamranahmedse/developer-roadmap#3956]
Add the coding section as well. As, some of the cyber security role requires the coding knowledge. I believe most of the candidates struggle at this part. To figure out how and what to prepare for the coding section in security engineer role. Rest all is tremendously impressive  job. Well done (y).

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
