### ISSUE TITLE
[Suggestion] Cyber Security Expert

### ISSUE THREAD

**Issue by 0xcrypto** [kamranahmedse/developer-roadmap#3986]
Certifications are incorrectly categorized.

- CompTIA A+ and CompTIA Network+ help in getting started with networking but they are not security certifications.
- CompTIA Security+, GSEC, GPEN are beginner level certifications.
- GWAPT, CEH and OSCP are also considered beginner level but they are not easy. CEH has a requirement of authorized training or 2 years of experience.
- CISSP, CISA, and CISM are advanced certifications and have a requirement of 5 years of experience but they are also inclined towards management and leadership rather than technical expertise.
- GIAC is not a certificate in itself but the organization that gives GPEN, GWAPT etc.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
