### ISSUE TITLE
[Suggestion] C++ Developer

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#3987]
- Remove the "using namespace std" directives from the code snippets;
- Add range-based for loop, which simplifies iterating over elements;
```c++
for (int number : numbers) {
    // do something;
}
```
- Add locale header "simple use" explanation (setting the terminal/console to show characters in the people native language) with the function setlocale;
- Add [cppreference](https://en.cppreference.com/w/) on the References / Additional Resources area.;
- Arithmetic operators are duplicated: one in 102-basic-operations & one in 103-functions;
- Include/header guards should be explained earlier.
```cpp
#ifndef MY_HEADER_FILE.H
#define MY_HEADER_FILE.H

// my header file content;

#endif
```

**Comment by thesmallrock** [comment]
Opened the PR, don't know if you want to keep the commentary on the range-for loop, feel free to take it out, change order, etc.

**Comment by thesmallrock** [comment]
Oops, accidentally closed!!!

**Comment by thesmallrock** [comment]
I think it would be great to add a node about the [locale header](https://en.cppreference.com/w/cpp/locale/locale), since people aren't working with multithread in the beginning, problems shouldn't be common.

People tend to feel confused on how to make their consoles/terminals print characters with accents, etc.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
