### ISSUE TITLE
[Suggestion] Full Stack Developer

### ISSUE THREAD

**Issue by shehabahmed235** [kamranahmedse/developer-roadmap#4000]
in CSS you can add an arabic sources like [https://www.youtube.com/watch?v=qyVkLebgfzY&list=PLDoPjvoNmBAzhFD3niPAa1C1gXG4cs14J&index=3](url) this video have assignment for a every stack of lessons
and in practicing their is 4 designs like [https://youtu.be/_-eh8cwGGwg](url) design 1, [https://youtu.be/heuDmrEAgUA](url) design 2,[https://youtu.be/vkc99WHcDTk](url) design 3, [https://youtu.be/DflEcuzjsyA](url) design4. and in javascript thier is two parts:[https://youtu.be/gIGGhFlGgLI](url) part1, [https://youtu.be/FKrfis1W1tk](url) part2 and it is also with assignments like CSS course

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
