### ISSUE TITLE
[Suggestion] Full Stack Developer

### ISSUE THREAD

**Issue by TommyLeong** [kamranahmedse/developer-roadmap#4002]
More like overall UI suggestion.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/9990179/f8b13c75-4851-4059-828a-83c25779896e)

While updating status of a component, we need to click 3 times. 
1. Component
2. Dropdown
3. Dropdown value (`Done`, `In Progress`, `Skip`) 

Instead a quick one?
1. Hover to the component
2. Click on the status value (`Done`, `In Progress`, `Skip`)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
