### ISSUE TITLE
[Suggestion] Spring Boot Developer

### ISSUE THREAD

**Issue by SzymanskiFilip** [kamranahmedse/developer-roadmap#4005]
Remove the first link of the Spring Security -> OAuth2 called "Spring Boot - OAuth2 with JWT" and replace it with both the Spring Resource Server and Spring Authorization Server

**Comment by usmanmg01** [comment]
Welcome to Gboard clipboard, any text that you copy will be saved here.

**Comment by usmanmg01** [comment]
- @hussainweb

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
