### ISSUE TITLE
[Suggestion] Prompt Engineering Roadmap

### ISSUE THREAD

**Issue by renancleyson-dev** [kamranahmedse/developer-roadmap#4010]
The Prompt engineering roadmap is incomplete when considering all the possible usages for LLM with tools like Langchain and the alternatives to simple Text/Chat completion. There are also essential concepts about IA to cover that are currently game changers and friendly for non-ML engineers to know like embeddings, similarity, and basic IA tasks(e.g. classification).

I don't even think prompt engineering is a good idea for a roadmap, it fits much more like a topic for a roadmap. I suggest changing to something like LLM Engineering.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
