### ISSUE TITLE
[Suggestion] add Deno for running TypeScript

### ISSUE THREAD

**Issue by scarf005** [kamranahmedse/developer-roadmap#4014]
# Summary

![image](https://github.com/kamranahmedse/developer-roadmap/assets/54838975/b9115209-73fe-4681-8762-8f89f00b2c1a)

[Deno](https://deno.land/) could be included in the methods to run [typescript](https://roadmap.sh/typescript).

## Rationale

- deno is significantly faster to run than ts-node (up to 40x faster on a simple hello world program). this helps with learning as you can change a portion of code frequently and see the result immediately (with --watch option)
- no step required to install frequently used tools as they are shipped out of the box (formatter, linter, benchmark tool)

## Benchmark

```sh
 ~/r/l/frontend   develop $…  cat ./hello.ts
console.log("Hello, World!")

 ~/r/l/frontend   develop $…  hyperfine --warmup 20 'ts-node ./hello.ts' 'ts-node --swc ./hello.ts' 'deno run ./hello.ts'
Benchmark 1: ts-node ./hello.ts
  Time (mean ± σ):     680.3 ms ±  26.0 ms    [User: 1357.0 ms, System: 120.4 ms]
  Range (min … max):   646.2 ms … 728.8 ms    10 runs
 
Benchmark 2: ts-node --swc ./hello.ts
  Time (mean ± σ):     211.3 ms ±   2.4 ms    [User: 187.0 ms, System: 59.5 ms]
  Range (min … max):   207.3 ms … 214.6 ms    14 runs
 
Benchmark 3: deno run ./hello.ts
  Time (mean ± σ):      16.8 ms ±   0.5 ms    [User: 10.0 ms, System: 7.9 ms]
  Range (min … max):    16.2 ms …  21.1 ms    136 runs
 
Summary
  'deno run ./hello.ts' ran
   12.59 ± 0.42 times faster than 'ts-node --swc ./hello.ts'
   40.53 ± 2.00 times faster than 'ts-node ./hello.ts'
```

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
