### ISSUE TITLE
[NEW ROADMAP] Embedded Engineering

### ISSUE THREAD

**Issue by diogokuiaski** [kamranahmedse/developer-roadmap#4020]
# Proposed roadmap

- Hands-on, get an Arduino or ESP32
- C/C++ for embedded
  - Programming without standard libraries
  - Try not to use dynamic allocation
  - Compilers (gcc, iar, Keil, etc..)
  - IDEs (VScode, IAR, Keil, Eclipse, VisualStudio)
  - Patterns
    - Circular Buffers
    - State Machines
- Digital Electronics
  - Basic Binary logic
  - Logic Ports
  - LED
  - Motor Drivers
- Integrated Circuits
  - Schematics reading
  - Datasheet reading
  - General Purpose Input Output
  - Sensors & Actuators
  - Analogic-Digital Converter
- Board Layout
  - Know your hardware
  - Bill Of Materials
  - Basic on PCB design (Altium, Eagle)
- Microcontrollers
  - RISC / CISC
  - DSPs
  - Choosing a Microcontroller
    - Ram
    - Flash
    - Frequency
    - Number of IOs
- Flashing a microcontroller
  - Bare Metal
  - RTOS
    - FreeRTOS
    - Zephyr
    - ThreadX
  - Jtag Interface
  - Debugging
- Tooling
  - Using an oscilloscope
  - Using a logical analyzer
- Device Drivers
  - Abstracting Hardware - HAL
- Communication Protocols
  - ISO/OSI
  - UART, CAN, USB
  - HDLC
  - I2C
  - SPI / ModBus
  - Wifi / LoRa / Zigbee
- Embedded Linux
  - Yocto Project
  - uClinux
- IoT
  - MQ queue (MQTT)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
