### ISSUE TITLE
[New Roadmap] Machine Learning

### ISSUE THREAD

**Issue by PriyansuMaurya** [kamranahmedse/developer-roadmap#4057]
Here is what I would suggest adding 

![ml-engineer](https://github.com/kamranahmedse/developer-roadmap/assets/101447544/6181aaea-79ba-4a9e-aff6-9ab3e6be0dc1)

**Comment by PriyansuMaurya** [comment]
Alright, I will include it and get back to you ASAP.

**Comment by thetinshusasi** [comment]
That would be great

**Comment by PriyansuMaurya** [comment]
I am currently at a rudimentary level. Despite that, I have made an attempt. However, I'm not entirely sure what more I should add.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/101447544/84dc9598-9778-458b-a092-b202b8b74bee)

I have created this Figma jamboard, so we can easily collaborate. Can anyone please help with this?

Here is the link : https://www.figma.com/file/J2sYb9BRpr3xwTT4jgk85w/ml-roadmap?type=whiteboard&node-id=0%3A1&t=NBfeBihCBRJMjEea-1

**Comment by PriyansuMaurya** [comment]
@letsmakecakes, bro can you help?

**Comment by letsmakecakes** [comment]
> @letsmakecakes, bro can you help?

Can I give you suggestions rather than helping with the design in Figma?

**Comment by PriyansuMaurya** [comment]
It's a piece of cake for anyone, I promise, we could take a meet.

**Comment by letsmakecakes** [comment]
> It's a piece of cake for anyone, I promise, we could take a meet.

Sure

**Comment by PriyansuMaurya** [comment]
When is the good time to do this?

**Comment by letsmakecakes** [comment]
> When is the good time to do this?

What's the best cafe in Mumbai?

**Comment by PriyansuMaurya** [comment]
Bro, I meant Google Meet?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
