### ISSUE TITLE
[Broken Link] Backend Developer

### ISSUE THREAD

**Issue by Ali-Tofiqi** [kamranahmedse/developer-roadmap#4067]
In Backend Developer path Internet > What is HTTP? > [SSL, TLS, HTTPS Explained](https://www.youtube.com/watch?v=j9qmmewmcfo) The video isn't available anymore in Youtube.

**Comment by ArnavK-09** [comment]
## **Fixed in** #4081

**Comment by ArnavK-09** [comment]
> In Backend Developer path Internet > What is HTTP? > [SSL, TLS, HTTPS Explained](https://www.youtube.com/watch?v=j9qmmewmcfo) The video isn't available anymore in Youtube. 
@Ali-Tofiqi 

## **Fixed in** #4081

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
