### ISSUE TITLE
[Suggestion] C   Developer

### ISSUE THREAD

**Issue by abhayaman669** [kamranahmedse/developer-roadmap#4071]
The suggested link (https://www.youtube.com/watch?v=vlnpwxzdw4y) in the **What is C++** section is not opening. I think it's better to have some options for voting over the suggested links so nonworking links can be removed (or maybe there is some other better way to do that).

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
