### ISSUE TITLE
[Suggestion] C   Developer

### ISSUE THREAD

**Issue by abhayaman669** [kamranahmedse/developer-roadmap#4086]
In the "running your first program" section, we currently have the following:

- [x] Write the first hello world program.
- [x] Explanation of the first program 

What we don't have

- [ ] Creating and saving the file (i.e. making a file with the `.cpp` extension)
- [ ] Running that file  (for all the different OS)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
