### ISSUE TITLE
[Suggestion] Cyber Security Expert

### ISSUE THREAD

**Issue by ag14spirit** [kamranahmedse/developer-roadmap#4089]
What about VNC protocol in addition to RDP? I realize they're not apples to apples, but with RDP as a proprietary tool and VNC more platform agnostic, it may be a worthwhile addition!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
