### ISSUE TITLE
[Suggestion] Allow roadmaps to be downloaded as md files

### ISSUE THREAD

**Issue by devhindo** [kamranahmedse/developer-roadmap#4097]
allow the roadmaps to be exported as `.md` files to be in the shape of a `markmap`. for personal edit, addition and deletion.

check [dundalek/markmap](https://github.com/dundalek/markmap) for more inspiration
[markmap vscode extension](https://github.com/markmap/markmap) also

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
