### ISSUE TITLE
[Suggestion] Blockchain Developer

### ISSUE THREAD

**Issue by cvanert** [kamranahmedse/developer-roadmap#4099]
Under 'Decentralization', the second article, "What Is Decentralization in Blockchain? (Blockchain Council), is essentially the same as the first article on AWS. It honestly looks like they took the article and just changed certain words/terms, like you would in school, to avoid plagiarizing. Diction choices were poor and made it more convoluted as opposed to reiterating the same content in a way that would help retain it. I don't think it's worth keeping.

Also, thank you for this resource.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
