### ISSUE TITLE
[Suggestion] Full Stack Developer

### ISSUE THREAD

**Issue by jimmyhogerty** [kamranahmedse/developer-roadmap#4113]
Just a nice-to-have, but if there are options to learn (i.e. `Node.js` here), it would be cool if users could select different replacement languages from the dropdown, such as Go or Python.

This would let me check Go's resources that you've gathered right from this view.

<img width="974" alt="Screenshot 2023-06-23 at 7 07 28 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/43115008/7b24673c-891c-4dfb-8d68-9c0bba1d26d0">

<img width="620" alt="Screenshot 2023-06-23 at 7 07 53 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/43115008/ccf857f8-f02c-4d39-927b-59e8e7d32e83">

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
