### ISSUE TITLE
[Suggestion] Frontend Performance Best Practices

### ISSUE THREAD

**Issue by ScottReed** [kamranahmedse/developer-roadmap#4133]
GZIP / Brotli compression is enabled. I would tweak the wording of this, where it says "Use a compression method such as Gzip or Brotli to reduce the size of your JavaScript files." I would suggest that it should be, enable compression methods such as Gzip and Brotli to to reduce the size of your requests (such as JavaScript, CSS and HTML). Favour Brotli over GZip where possible due to performance benefits of 14% smaller JavaScript files, 21% smaller HTML files and 17% smaller CSS files over Gzip. Also if using a CDN such as Cloudflare/Akami make sure that the CDN is setup to enable Brotli compression.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
