### ISSUE TITLE
[Bug] "Buffer" card in Go roadmap has a resource for protocol buffers.

### ISSUE THREAD

**Issue by its-kos** [kamranahmedse/developer-roadmap#4136]
The card "Buffer" on the Go roadmap has a link called "Buffers in Golang" that points to [this](https://youtu.be/NoDRq6Twkts) video. The video is about protocol buffers and there's a specific card about protocol buffers later on in the roadmap. The resource should be moved to the "Protocol Buffers" card.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
