### ISSUE TITLE
[Suggestion] DevOps Roadmap

### ISSUE THREAD

**Issue by afcruzc** [kamranahmedse/developer-roadmap#4139]
Hello,

First I would like to thank you for taking the time to build this valuable content. I propose that you could make a small change in the order of the main topics to place the network, security and protocols topics, followed by the VCS Hosting topic, keeping in mind that to properly understand the concepts of web servers, firewalls, load balancing, containers and cloud services, it is important to understand the networking and protocols concepts. Thanks for sharing with the community.

Have a nice day.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
