### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by LucianIoan31** [kamranahmedse/developer-roadmap#4162]
Hello!

It would be great if you would implement a feature that allows users to check when they finish a lesson from every section. I have attached a file so you can understand better what I mean. It would be such a great help if you would do this for me. :)
![example](https://github.com/kamranahmedse/developer-roadmap/assets/82084841/57b6b1f1-5e6a-4809-b9bd-4e882fbcba4f)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
