### ISSUE TITLE
Test Management

### ISSUE THREAD

**Issue by AdeTesting** [kamranahmedse/developer-roadmap#4190]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

Hi,
the roadmap is great but only follows "execution" roles. A QA engineer, manual or automation, can easily grow towards test management/defect management/release management and these are useful skills to add.
Please look into that, or feel free to reach out to me if you need more specific contributions. The roadmap as-is now would cover maybe 3-4 years of career progression in manual, with quite a lot more in automation simply because the tech keeps evolving and you need to learn it, not because you get to do anything dramatically different.
So, as far as QA goes, we still lack vision over how a length career can look like and this puts off many people who do not want to be in execution jobs for decades. I am one of them.

**Comment by Arsh551** [comment]
Useful Suggestion

**Comment by kamranahmedse** [comment]
Thank you for the suggestion. What do you think we can add and where in the roadmap? Feel free to suggest a nested bullet list mentioning the nodes to be added.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
