### ISSUE TITLE
Consistency Patterns are Insufficient

### ISSUE THREAD

**Issue by PeterPCW** [kamranahmedse/developer-roadmap#4192]
### Roadmap URL

https://roadmap.sh/system-design

### Suggestions

The Consistency Patterns topic mentions 3 patterns but makes no attempt to even summarize them before the external link.

The 3 separate pages then do a poor job of defining the patterns too, relative to the link (same on all 4 pages), which is copied verbatim on Consistency Patterns.

I see two options:
1. Convert Consistency Patterns into a page like CAP above it where the subpages are really just one page when clicked. (preferred)
2. Update Consistency Patterns with some info on the three, ie:
"Strong consistency - synchronous update everywhere
Weak consistency - synchronous locally (ie multiplayer game) but asynchronous globally
Eventual Consistency - asynchronous and indeterminate"
2a. Ideally improve the subpages too if they remain.

**Comment by PeterPCW** [comment]
Actually an even better example is the Fail-Over topic. Consistency Patterns should look like that.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
