### ISSUE TITLE
JavaScript Roadmap

### ISSUE THREAD

**Issue by ojhabhumika** [kamranahmedse/developer-roadmap#4193]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

We can add one more node in the JavaScript roadmap
Web Storage Mechanisms - 

1. Local Storage
2. Session Storage
3. Cookies

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
