### ISSUE TITLE
C++ Frameworks

### ISSUE THREAD

**Issue by Vakulex** [kamranahmedse/developer-roadmap#4200]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

Hi, in my opinion it'd be great to add Unreal Engine or other game engines to framework list, since, basically, game engines **are** frameworks.
Thank you in advance, best regards

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
