### ISSUE TITLE
I want to suggest the LAMP/WAMP stack expecially PHP roadmap.

### ISSUE THREAD

**Issue by abdulsalamamtech** [kamranahmedse/developer-roadmap#4214]
### Feature Description

I really love the way you organize the road map on your website (roadmap.sh).
I want to suggest you add the LAMP/WAMP stack format, including the PHP and his framework (i.e Laravel).
I would really love to get your feedback as soon as possible.
You get reach me on [LinkedIn](https://www.linkedin.com/in/AbdulsalamAmtech), [Facebook](https://www.facebook.com/AbdulsalamAmtech) or [Twitter.](https://www.twitter.com/AbdulsalamTech)
Also this is my email: AbdulsalamAmtech@gmail.com

**Comment by yunygo** [comment]
More detailed roadmap about php . 😊

**Comment by abdulsalamamtech** [comment]
yes

**Comment by simone-boa-ideas** [comment]
I think that Laravel deserves a roadmap of its own 😄
There is so much to cover there!

**Comment by iPoetDev** [comment]
I first used PHP 20 years ago, now I come back to it.

So I created my own custom PHP roadmap from their docs and from PHP books TOC of amazon.

Proof Of Concept/ WIP: https://roadmap.sh/r?id=65bd25950c54812283803899

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by abdulsalamamtech** [comment]
It's great hearing from you.
Thanks.
