### ISSUE TITLE
Add OWASP LLM's to Prompt Engineering path

### ISSUE THREAD

**Issue by davidgraca** [kamranahmedse/developer-roadmap#4222]
### Roadmap URL

https://roadmap.sh/prompt-engineering

### Suggestions

Hello, 
OWASP is the reference institution for application security, they now have their recomendations on LLM's security https://owasp.org/www-project-top-10-for-large-language-model-applications/
It is a great addition to the roadmap.
Best regards,
DAvid

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
