### ISSUE TITLE
JavaScript Roadmap Addition

### ISSUE THREAD

**Issue by kaustavkarak** [kamranahmedse/developer-roadmap#4227]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Please add "Ternary Operator" in "Expressions and Operators" section

**Comment by aricma** [comment]
Hey @kaustavkarak, I think we close this issue. We already have conditional operators in the javascript roadmap.

<img width="1201" alt="Screenshot 2023-07-26 at 09 47 25" src="https://github.com/kamranahmedse/developer-roadmap/assets/22852149/ba499287-5e27-405b-b7d7-a0edace0b9dd">

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
