### ISSUE TITLE
Change style of references/pointers

### ISSUE THREAD

**Issue by AlexOteiza** [kamranahmedse/developer-roadmap#4229]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

Code examples have the & and * next to the variable name instead of the type.
example:
```
int num = 10;
int *ptr = &num;  // Pointer 'ptr' now points to the memory address of 'num'
```

This might confuse new C++ programmers when attempting to learn about the language. isocpp core guidelines states that declarators reference must be next to the type: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl18-use-c-style-declarator-layout

```
T& operator[](size_t);   // OK
T &operator[](size_t);   // just strange
T & operator[](size_t);   // undecided
```

**Comment by kamranahmedse** [comment]
Thanks Alex, feel free to open a PR

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
