### ISSUE TITLE
You need to change the color of the status in the process. It's too hard to see clearly

### ISSUE THREAD

**Issue by Moclaw** [kamranahmedse/developer-roadmap#4230]
### Roadmap URL

https://roadmap.sh/aspnet-core

### Suggestions

You need to change the color of the status in the process. It's too hard to see clearly. I suggest using a blue color as it would make it easier to see

**Comment by kamranahmedse** [comment]
Which color are you talking about?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
