### ISSUE TITLE
Include tools for unit testing

### ISSUE THREAD

**Issue by Antoniobox** [kamranahmedse/developer-roadmap#4237]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

Nowadays, the use of software to perform unit tests is often seen in many projects. It would be interesting to include it in the roadmap, at least to get a general idea. Thanks for reading.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
