### ISSUE TITLE
Temporal Dead Zone / Hoisting

### ISSUE THREAD

**Issue by mhmdmsvi24** [kamranahmedse/developer-roadmap#4247]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

in order to having **Hoisting** in the roadmap for variables and functions it'll be great adding **TDZ or Temporal Dead Zone** concept too so learners can also learn about **Let** keyword too along side Hoisting for **Var** and **Functions**. Thanks for the roadmap 💖😀.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
