### ISSUE TITLE
Pdf roadmap react is not up to date.

### ISSUE THREAD

**Issue by romanbtt** [kamranahmedse/developer-roadmap#4248]
### What is the URL where the issue is happening

https://roadmap.sh/pdfs/roadmaps/react.pdf

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The rtk-query module is missing in the APICalls section in the pdf version.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JamieBort** [comment]
I'll gladly address this.
However I am new to this repo. I am not sure where to start.
Does it exist anywhere in the documentation? Do I need to create the PDF?
Any and all feedback is greatly appreciated. Thanks!

**Comment by dansholds** [comment]
Thanks for raising this @romanbtt! I've created an internal ticket to tackle this.

@JamieBort I love the desire to fix this from your end but it's unfortunetly not possible for you to do at this moment in time.

If you're keen to collaborate on the repo than join our Discord (if you haven't already!) (https://discord.gg/FyaRFe5e) where we have a collaborators channel where we can have more real-time discussions around the do's & don't aswell as the can's & cannots of contributing to the project!

**Comment by JamieBort** [comment]
Thanks for the Discord link, @dansholds! I am in the middle of a different Issue at the moment. But when I have some free time I'll circle back around here and start with the Discord.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
