### ISSUE TITLE
Add a learning programming language to qa roadmap

### ISSUE THREAD

**Issue by rggaoxin** [kamranahmedse/developer-roadmap#4260]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

I think programming language is the base for automation testing. And I think we can add learning programming language before automation test. 
First step, we can learn the base for python or java. Add it before automation test.
Second step, we need to learn more about programming language, such as web firmware. We can use the firmware to develop the

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by rggaoxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
