### ISSUE TITLE
Project ideas for the DevOps Roadmap

### ISSUE THREAD

**Issue by Jojo-GitH2** [kamranahmedse/developer-roadmap#4270]
### Feature Description

I went through the DevOps roadmap and it was wonderful though, I didn't see project ideas or something of that sort included. It would be nice to put the knowledge gained from the roadmap into practice at least at certain points of the roadmap.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
