### ISSUE TITLE
unavailable youtube videos in c++ roadmap bitwise operators

### ISSUE THREAD

**Issue by samyarkhafan** [kamranahmedse/developer-roadmap#4273]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

the videos linked in the bitwise operators section no longer exist and need to be updated.

**Comment by mnamesujit** [comment]
Hello Sir can i work on this  issue?

**Comment by samyarkhafan** [comment]
Idk can you? Someone needs to update the links to those videos with something else cause the old ones are removed from youtube.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
