### ISSUE TITLE
Dynamic programming section for the computer science roadmap

### ISSUE THREAD

**Issue by aitmamatovmusa** [kamranahmedse/developer-roadmap#4274]
## Problem:
I don't see dynamic programming section in the computer science roadmap, it would be great to see it

## Links:
- https://www.programiz.com/dsa/dynamic-programming
- https://www.geeksforgeeks.org/dynamic-programming/

## Problems on Leetcode:
- https://leetcode.com/problems/fibonacci-number/
- https://leetcode.com/problems/climbing-stairs/
- https://leetcode.com/problems/jump-game/

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
