### ISSUE TITLE
Add CASP+ next to CEH

### ISSUE THREAD

**Issue by noshitsecurity** [kamranahmedse/developer-roadmap#4276]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Add the CASP+ certification right next to CEH since the industry loves to hate them both yet won't deny their legitimacy

-Shane

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
