### ISSUE TITLE
add info on lexing/parsing & compilers to Comp Sci roadmap

### ISSUE THREAD

**Issue by jnahmias** [kamranahmedse/developer-roadmap#4277]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

Unless I missed it (entirely possible), I didn't see any mention of compilers and specifically lexing/parsing on the Computer Science roadmap. Seems to me that this should be at least mentioned with some discussion of different algorithms, approaches, and tools. (eg. top-down, bottom-up, recursive descent, LL, LR, ANTLR, lex/yacc.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by jnahmias** [comment]
Still an issue. Feel free to close as wontfix if you don't want to do this. But, honestly, if you can't be bothered to check if the issue has already been resolved before closing I'm not sure why you bother having a public issue tracker.
