### ISSUE TITLE
Add compilers to Computer Science Roadmap

### ISSUE THREAD

**Issue by Yarillo4** [kamranahmedse/developer-roadmap#4283]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

Hey

I feel like most CS curricula include something about formal grammars, parsers and compilers. I feel like we all end up doing a fair bit of parsing in our professional life too.

There's a lot of resources online, mostly scholarly, I haven't checked on Khanacademy or the like yet but here are my findings .

**Tel Aviv University:**

* With this [great article](https://blog.sigplan.org/2021/02/23/teaching-compilers-backward/), "Teaching compilers backwards" and the resulting course
  * https://www.cs.tau.ac.il/research/yotam.feldman/courses/wcc20/wcc20.html
  * https://www.cs.tau.ac.il/~msagiv/courses/wcc20.html

**"Crafting interpreters":**

* https://craftinginterpreters.com/contents.html

**UCSD:**

* https://cseweb.ucsd.edu/classes/sp17/cse131-a/
* https://podcast.ucsd.edu/podcasts/default.aspx?PodcastId=4014
* https://github.com/ucsd-cse131-sp17

**Earlier UCSD offering:**

* https://www.cs.swarthmore.edu/~jpolitz/cs75/s16/

**Matt Might's course:**

* https://matt.might.net/teaching/compilers/spring-2015/

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
