### ISSUE TITLE
Remove checkmarks from the corner of the boxes for clarity and redesign the color system of the boxes.

### ISSUE THREAD

**Issue by Dago-117** [kamranahmedse/developer-roadmap#4295]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

The website is amazing, but I think this suggestion would make it more intuitive for people who are new to the site. I understand the checkmark icons are there to specify the level of recommendation, but I don't think that adds a lot to the roadmap. For a new user, like me, we don't know who is recommending or not the lesson. If the creator of the site (who the new user assumes is the one posting the lessons) is not recommending the lesson, then why have it there? 
The icon of a checkmark most of the time implies something is done, especially when the checkmark or the checkmark container is green. 
The color of the box should change according to the color of the status we select inside the lesson where the links are. Changing, the lesson to "in progress", which has a yellow-ish icon turns the box to the color purple, and changing it to "done", which is green, changes it to another shade of the previous yellowish color but with a strike line. 
I think what I am trying to say is that there should be more consistency with the use of colors. 
If the level of recommendation icons were to stay, I would suggest removing the checkmark and leaving only the circle, while using a color scheme different from the colors used in the boxes and the colors used in the status options.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
