### ISSUE TITLE
DevSecOps, Identity, & Cloud Enhancement

### ISSUE THREAD

**Issue by SMBowen** [kamranahmedse/developer-roadmap#4296]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Entire section missing on Software Security...should include at least
SSDF (Secure Software Development Framework)
OpenSAMM (Software Assurance Maturity Model)
BSIMM (Build Security In Maturity Model)
SBOM
SCA
SAST
DAST
RASP

There should be a section on Identity as well: ICAM, IGA, Secrets Management, PIM, PAM, EPM, MFA, Passwordless, CIAM, Identity Protection

Cloud should have some required knowledge around CSPM, CWPP, CNAPP, & CASB

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by DN4Davi** [comment]
The roadmap still lacks on these topics. The CyberSecurity roadmap is more long than necessary at the same tima that lacks on actually important topics.
