### ISSUE TITLE
C++ Developer roadmap - Setting up your environment - Misinformation on availability of Visual Studio on Mac

### ISSUE THREAD

**Issue by PatrykSzewczuk** [kamranahmedse/developer-roadmap#4299]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

As mentioned in the title, there appears to be misinformation on the availability of Visual Studio on Mac. Although Visual Studio has a Mac version, it is different from the Windows version. The MacOS version of Visual Studio code only supports .NET development, therefore lacking support for C++. Of course there are other IDE's, but it would be nice to list Visual Studio as Windows only option. Thanks

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
