### ISSUE TITLE
Missing completion functionality under multiple sections

### ISSUE THREAD

**Issue by 7864214** [kamranahmedse/developer-roadmap#4302]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

17 sections under the cyber-security roadmap cannot be marked as complete. The understand audience section is unresponsive cannot be clicked on.  
![image](https://github.com/kamranahmedse/developer-roadmap/assets/25224390/23eb9708-b43a-4e7f-8511-b3f0d9d23512)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Thanks for this, I have created an internal ticket to tackle this as it makes the Cyber Security roadmap impossible to complete!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
