### ISSUE TITLE
Array Destructuring in JavaScript

### ISSUE THREAD

**Issue by sai6708** [kamranahmedse/developer-roadmap#4310]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Array Destructing needs to be added under the concept of the array which is supported by javascript.

https://www.freecodecamp.org/news/array-vs-object-destructuring-in-javascript/
https://www.youtube.com/watch?v=giNjEgYTd9E&list=PLsyeobzWxl7rrvgG7MLNIMSTzVCDZZcT4&index=37&ab_channel=Telusko

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
