### ISSUE TITLE
Bookmark links 

### ISSUE THREAD

**Issue by PhStefen** [kamranahmedse/developer-roadmap#4311]
### Bookmark link

First of all, great job everyone! I love this project.

I would like to have the ability to save/bookmark the links I have already clicked/read. Occasionally, I have to jot down which link I visited

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
