### ISSUE TITLE
Where's Dates?

### ISSUE THREAD

**Issue by pedro-demeu** [kamranahmedse/developer-roadmap#4313]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Why in javascript roadmap, has no Date recomendation? I think that it's very important for any  js student 

tree example:

Dates -> Timezones
          -> DayJs / Date FN  / d3 / etc
          -> Udp  / toIsoString( )

**Comment by MavGitt** [comment]
Agree +1

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
