### ISSUE TITLE
Strikethrough text on Done status makes text difficult to read

### ISSUE THREAD

**Issue by abdulwahabse** [kamranahmedse/developer-roadmap#4314]
### Roadmap URL

https://roadmap.sh/

### Suggestions

When we mark a node as "Done" then the color changes with a strikethrough appears on the text. While the color is fine, the strikethrough text makes it difficult to read. Can you please change the design that would enhance the readability on Done state? Thank you :)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by nayananandofficial** [comment]
Hi, I would also add one. 

Now roadmap.sh has this feature where you can personalize any roadmap using the in-built Ai feature. You can even switch between the personalized and the original roadmap. The problem I currently noticed is that, when the personalized roadmap is created it strikes some topics off and this might create confusion of whether the unstriked are the personalized topics or the opposite.
