### ISSUE TITLE
Image Prompting Improvements

### ISSUE THREAD

**Issue by chints-me** [kamranahmedse/developer-roadmap#4315]
### Roadmap URL

https://roadmap.sh/prompt-engineering

### Suggestions

In the Image Prompting section, you could add more sub-topics to it in the following order.

- Style Modifiers (Exists with the link broken, submitted a new link)
- Quality Boosters (Submitted a new link)
- Repetitions (Add new this sub-topic)
- Weighted Terms (Submitted a new link)
- Fix Deformed Generations (Submitted a new link)
- Shot Type (Add new this sub-topic)
- Midjourney (Add new this sub-topic)

All the links are provided here:
- Style Modifiers (https://learnprompting.org/docs/image_prompting/style_modifiers)
- Quality Boosters (https://learnprompting.org/docs/image_prompting/quality_boosters)
- Repetitions (https://learnprompting.org/docs/image_prompting/repetition)
- Weighted Terms (https://learnprompting.org/docs/image_prompting/weighted_terms)
- Fix Deformed Generations (https://learnprompting.org/docs/image_prompting/fix_deformed_generations)
- Shot Type (https://learnprompting.org/docs/image_prompting/shot_type)
- Midjourney (https://learnprompting.org/docs/image_prompting/midjourney)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
