### ISSUE TITLE
Add Root Me to the CTFs section

### ISSUE THREAD

**Issue by HooperDooper** [kamranahmedse/developer-roadmap#4318]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Hello, i suggest you guys to add "Root-me" [https://www.root-me.org/] to the "CFTs" section, its a really good place to practice Hacking skills.

Keep on your awsome work

With <3 

++

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
