### ISSUE TITLE
Add more of the INE/elearnsecurity exams for cyber certifications

### ISSUE THREAD

**Issue by jaedyno15** [kamranahmedse/developer-roadmap#4319]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Add the eJPT ([junior penetration tester)](https://ine.com/learning/certifications/internal/elearnsecurity-junior-penetration-tester-cert?_gl=1*fgrd65*_gcl_au*MTM1NTk2MzU0Ni4xNjgxMTQxNTM1) as a beginner certification, eCPPT ([Certified Professional Penetration Tester)](https://elearnsecurity.com/product/ecpptv2-certification/) as the end of beginner heading to advanced cert, eWPT ([Web Application Penetration Tester)](https://elearnsecurity.com/product/ewpt-certification/) again as medium to complex, and eWPTX ([Web Application Penetration Tester eXtreme)](https://elearnsecurity.com/product/ewptxv2-certification/) as a very hard one. 

I have taken the first of these exams and I know that they are well-regarded in the industry. They give a hands-on approach to examinations as they are dynamic labs (as opposed to just theory-based) which provides a better view of someone's abilities. 

The current ones are a lot more focused on more general IT. Additionally, you could have different certification sections depending on the skillset people are going for. Here's a good site that show's a bunch of certifications and what category they fall under [security-certification-roadmap](https://pauljerimy.com/security-certification-roadmap/).

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
