### ISSUE TITLE
Adding Gui Programming to Java Roadmap

### ISSUE THREAD

**Issue by Koko1345** [kamranahmedse/developer-roadmap#4321]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

By using the Java Roadmap on your website. I noticed that Java swing and awt are not in the roadmap. Or in general there is no GUI programming in the roadmap. And in my opinion its very important and I would suggest to add this.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
