### ISSUE TITLE
Changes in Checkpoint - CLI Apps

### ISSUE THREAD

**Issue by SatyamSakpal** [kamranahmedse/developer-roadmap#4323]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

This checkpoint suggests applications that one can make after learning node js,  though there might be some problem in the first suggestion as the suggestion says.

"Create a CLI application that takes a URL and a CSS selector arguments and prints the text content of the element that matches the selector. Hint you can use [cheerio](https://github.com/cheeriojs/cheerio)"

When I checked it, it appears that the **_cheerio module is not fully built yet_** so the main function to do the above task ( cheerio.fromURL() ) is not out yet. Which might create **confusion amongst learners.**

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
