### ISSUE TITLE
Backend & Frontend

### ISSUE THREAD

**Issue by firedevelop** [kamranahmedse/developer-roadmap#4326]
### Feature Description

if you can add some place for:

**Backend Developer**
[Google idx.dev](https://idx.dev/)
[vercel](https://vercel.com/)

**Frontend** / CSS Branch:
[nextui.org](https://nextui.org/)
[ant.design](https://ant.design/)

congratulations, amazing site!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
