### ISSUE TITLE
C++ RoadMap PDF File is found attached after clicking download button of React-Native RoadMap.  

### ISSUE THREAD

**Issue by pmbharali** [kamranahmedse/developer-roadmap#4328]
### Roadmap URL

https://roadmap.sh/react-native

### Suggestions

Please replace the C++ pdf file attached with download button of React-Native RoadMap with the pdf file of React-Native RoadMap.

**Comment by itvexesme** [comment]
The issue persists for me too. The URL to download the React Native roadmap is https://roadmap.sh/pdfs/roadmaps/react-native.pdf. It contains the C++ roadmap as the first page and the React Native roadmap as the second page.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
