### ISSUE TITLE
Toggle difficulty levels (on/off)

### ISSUE THREAD

**Issue by projectmehari** [kamranahmedse/developer-roadmap#4331]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

It would be easier on the eye if we could toggle the difficulty levels ( beginner/ intermediate/advanced). it would definitely improve the roadmaps in terms of accessibility.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
