### ISSUE TITLE
Add IndexDB into Front end roadmap

### ISSUE THREAD

**Issue by rickvian** [kamranahmedse/developer-roadmap#4334]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Hi, i didn't see IndexDB in front end roadmap, 
i think it can be separate but optional beside web storage

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
