### ISSUE TITLE
Center Modal Window

### ISSUE THREAD

**Issue by randylirano** [kamranahmedse/developer-roadmap#4335]
### Roadmap URL

https://roadmap.sh/system-design

### Suggestions

Whenever I clicked content in the roadmap, it is always displayed in the pop-up right panel.

Example:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/31170227/77c9c535-ea63-4ca6-847e-5a2d50cae3e5)

When I open the **Performance vs Scalability** section, only a small portion at the right of my screen actually displays the materials.

Since the content of the roadmap is the main focus, would it be possible to have it displayed at the center of the screen?
Let me know your thoughts.
Thank you.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
