### ISSUE TITLE
Python Developper Roadmap

### ISSUE THREAD

**Issue by AD0791** [kamranahmedse/developer-roadmap#4336]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

# addition in the roadmap

1. Pymongo -> basic ODM for mongodb
2. Motors-> build on top of Pymongo -> ODM for mongo
3. SQLAlchemy -> toolkit for sql databse -> ORM
4. SQLMODEL -> build on top of pydantic and sqlalchemy -> build by Tiangolo, author of FASTAPI
5. Pydantic -> ydantic is the most widely used data validation library for Python. -> essential for serialization process with type annotation in the FASTAPI -> Flask has a Flask-pydantic wrapper that will help you work with pydantic in the context of a flask app.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
