### ISSUE TITLE
Request List My New Tool 

### ISSUE THREAD

**Issue by dragonked2** [kamranahmedse/developer-roadmap#4337]
### Feature Description

I Would Like To Request Adding My New Tool To Your Github Top List 
https://github.com/dragonked2/Egyscan

![image_2023-07-22_23-40-22 (2)](https://github.com/freeCodeCamp/freeCodeCamp/assets/66541902/d0cc6f12-de02-4dee-bae3-1a9ee764d4dc)

![[Image](og:image)](http://156.223.131.194:4444/)
![[Image](og:image)](http://156.223.131.194:80/index.php)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
