### ISSUE TITLE
Changes in Static Typing (C++ Developer)

### ISSUE THREAD

**Issue by Mikeost** [kamranahmedse/developer-roadmap#4338]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

The text says that a compile-time error will occur in this block of code:
```
int num = 42;        // 'num' is statically typed as an integer
double pi = 3.14159; // 'pi' is statically typed as a double

num = pi; // This assignment would cause a compile-time error as the types don't match
```
However, there will be NO error here. There will be an implicit type conversion and code will compile.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
