### ISSUE TITLE
Python Developer - dependency management

### ISSUE THREAD

**Issue by skoenig** [kamranahmedse/developer-roadmap#4349]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

I suggest to include a node about Python dependency management and the ecosystem around it. Since this is a broad topic with a lot of different approaches and tools this could confuse a new Python developer. An explanation of how dependencies have been managed historically (`requirements.txt`) and what is the modern solution (`pyproject.toml`) could provide some guidance.
I realize that this is somewhat related to Python package managers, but perhaps deserves an own node.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
