### ISSUE TITLE
Add AnalogJS to SSR/SSG roadmap

### ISSUE THREAD

**Issue by AdditionAddict** [kamranahmedse/developer-roadmap#4350]
### Roadmap URL

https://roadmap.sh/angular

### Suggestions

AnalogJS is a meta framework that does SSR/SSG as well as doing some meta-framework things like file-based routing

Note: Scully only officially supports Angular v12 and last had a commit a year ago

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
