### ISSUE TITLE
Proposal for roadmap.sh Enhancement: Automatic Removal of Skipped Steps

### ISSUE THREAD

**Issue by CryptoLevchyk** [kamranahmedse/developer-roadmap#4351]
### Suggestions

Hello, I would like to propose an enhancement for roadmap.sh regarding the display of steps on the roadmap. 

Currently, when I skip a step, it simply becomes a darker color, and this is no comfortable. 

My idea is to automatically remove the skipped steps from the roadmap instead of just changing their colors. 

Additionally, I suggest adding a separate page or button at the top of the navigation bar where all the skipped steps would be stored. 

This would allow me to easily review and add these steps to the roadmap if I change my plans regarding them. 

I believe that this change will add more convenience and clarity to the usage of roadmap.sh. 

Thank you for considering my proposal.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
