### ISSUE TITLE
Changes to Virtualization Section of Cyber Security Roadmap

### ISSUE THREAD

**Issue by spencerdclayton** [kamranahmedse/developer-roadmap#4353]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

**Common Virtualization Technologies** should be renamed to **Common Virtualization Software**.
List of items should be changed to ESXi, Hyper-V, KVM. 
Examples of KVM can include Proxmox, TrueNAS, and virtmanager.

Reason:
Currently it lists VMWare, VirtualBox, esxi, and proxmox.
ESXi is software made by VMWare (possible original author meant VMWare workstation)
VirtualBox and VMWare workstation are useful tools but not enterprise grade, you would be better served by interacting with Hyper-V and KVM (free) or ESXi which are all widely used in enterprise applications.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
