### ISSUE TITLE
Slight changes

### ISSUE THREAD

**Issue by aaliyevaa** [kamranahmedse/developer-roadmap#4355]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

The roadmap for cybersecurity is good overall, but my suggestion is making it similar to AI,Data Science one. Because AI roadmap is much easier to understand and follow along, while Cybersecurity roadmap is much more complicated. It confuses me where to start, what to learn next and so on
Thank you

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
