### ISSUE TITLE
Difference in PDF and Web version in Flutter roadmap

### ISSUE THREAD

**Issue by d-rooX** [kamranahmedse/developer-roadmap#4358]
### What is the URL where the issue is happening

https://roadmap.sh/flutter

### What browsers are you seeing the problem on?

Any

### Describe the Bug

There is difference in "State Management" section between web version of roadmap and PDF for downloading.
There is no options in web version such as "Get X" and "Velocity X" for example. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
