### ISSUE TITLE
Globalization features

### ISSUE THREAD

**Issue by brunoj1** [kamranahmedse/developer-roadmap#4359]
### Roadmap URL

https://roadmap.sh

### Suggestions

Hi,

I really love the website and roadmaps that you guys provide. I wanted to share a roadmap to my local community on Brazil, was thinking of translating by myself but that´s not optimal, II would love to have a way to start translating roadmap to a specific language, so we can still use the same roadmap website but on a different language.

Thanks in advance.

**Comment by gu-alves** [comment]
I would be happy to contribute for PT-BR too!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
