### ISSUE TITLE
AI and Data Scientist Roadmap - Deep Learning Book Sugestion

### ISSUE THREAD

**Issue by elir0d** [kamranahmedse/developer-roadmap#4361]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

I believe that a good alternative to the current book is https://pt.d2l.ai/index.html

It is a great book a it is fully interactive with a lot of languages available.

**Comment by RajBusa** [comment]
https://github.com/kamranahmedse/developer-roadmap/pull/4556

I have considered your suggetion and have updated the back link of the ebook and is pending for review.

**Comment by elir0d** [comment]
Thank you!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
