### ISSUE TITLE
Add Vite in Fundamental Topics section

### ISSUE THREAD

**Issue by lotus34rus** [kamranahmedse/developer-roadmap#4369]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

Modern vue developers use not only the Vue CLI, but also VIte.
I think it would be nice to add a Vite block next to the Vue CLI.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
