### ISSUE TITLE
Prerequisites of the roadmaps

### ISSUE THREAD

**Issue by SahilDahat** [kamranahmedse/developer-roadmap#4370]
### Roadmap URL

https://roadmap.sh

### Suggestions

Include a preliminary requisites segment before the roadmap in order to ascertain whether users possess foundational knowledge requisite before starting the roadmap. For example in typescript roadmap, someone should know atleast the basics of javascript such that they can learn which is better, why is it better & compare them.

Thank you.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by CleverLemming1337** [comment]
I think this is still relevant.

For example if you just want to learn about one topic without doing everything before O think a short checklist of prerequisites were great.
