### ISSUE TITLE
Golang: Add Slog logging package

### ISSUE THREAD

**Issue by Broderick-Westrope** [kamranahmedse/developer-roadmap#4371]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions

For the Logging node, I think that [Slog](https://pkg.go.dev/log/slog) should be added as a sub-node. It was previously an experimental package, but [Go 1.21](https://go.dev/blog/go1.21) (now released) officially brought it into the standard library. This makes it the new standard for structured logging, and I think it would be helpful to teach those trying to learn Go to use packages from the standard library until they find a good reason not to.

I have found the following resources helpful in learning Slog, however I'm sure more will come out soon now that it is in the standard library:
- [Developer Cafe](https://thedevelopercafe.com/articles/logging-in-go-with-slog-a7bb489755c2)
- [Better Stack](https://betterstack.com/community/guides/logging/logging-in-go/)

Thanks for your great work!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
