### ISSUE TITLE
AWS Best Practices - S3 Use random strings at the start of your keys doesn't apply anymore

### ISSUE THREAD

**Issue by GauntStrelok** [kamranahmedse/developer-roadmap#4383]
### Roadmap URL

https://roadmap.sh/best-practices/aws

### Suggestions

There is a checkbox that says  Use random strings at the start of your keys.
This is no longer true since this post
https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-s3-announces-increased-request-rate-performance/

You can also checkout a question on SO
https://stackoverflow.com/questions/43035449/add-a-random-prefix-to-the-key-names-to-improve-s3-performance

There is an answer in SO that still recommends to do that.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
