### ISSUE TITLE
 [Suggestion] Python Developer

### ISSUE THREAD

**Issue by ada0l** [kamranahmedse/developer-roadmap#4407]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

1. You can add [poetry](https://python-poetry.org/) to package managers. It's a good alternative to pip
2. I'm surprised the roadmap doesn't have anything about typing and async

**Comment by kamranahmedse** [comment]
Thank you for the suggestion. We have some changes planned for the Python roadmap. What else do you think should be there? Feel free to provide a nested bullet list of topics you see missing.

**Comment by hong539** [comment]
Hey, I think the part is about the Python development environment setup.

And here is My little notes for these setup on Linux .

Method 1:
Usage with pyenv+poetry
Method 2:
Usage with pyenv+pipenv

Teleport link:
https://github.com/hong539/setup_dev_environment/blob/main/programming_languages/python/python.md#usage-with-pyenvpoetry

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
