### ISSUE TITLE
Installing a Local Cluster

### ISSUE THREAD

**Issue by hong539** [kamranahmedse/developer-roadmap#4411]
### Roadmap URL

https://roadmap.sh/kubernetes

### Suggestions

About Installing a Local Cluster part
Also, we can try to deploy a k8s cluster on our localhhost with this tools: kind/k3s/colima!

Teleport link:
kind
https://kind.sigs.k8s.io/

k3s
https://k3s.io/

colima
https://github.com/abiosoft/colima

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
