### ISSUE TITLE
"Installing C++": Easier/Quicker way to Install C++ compiler for Windows with a command

### ISSUE THREAD

**Issue by anb1142** [kamranahmedse/developer-roadmap#4412]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

Suggested changes for "Installing C++"
Easier/Quicker way to Install C++ compiler for Windows with a command

Execute this command In **powershell** with **administrator** privileges :
`Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('[https://chocolatey.org/install.ps1'))](https://chocolatey.org/install.ps1'))); choco install mingw -y`

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
