### ISSUE TITLE
Add Open Source Roadmap

### ISSUE THREAD

**Issue by ascodeasice** [kamranahmedse/developer-roadmap#4433]
### What is the title of the roadmap you are submitting?

Open Source Contribute Roadmap

### Is this roadmap prepared by you or someone else?

I prepared this roadmap

### Roadmap Items

- Introduction to Open Source
  - What is Open Source?
  - Why is Open Source Important?
  - Introduction to GitHub
- What to contribute
  - Issue
  - Pull Request
  - Code Review
- Git
  - Basic Usage
  - Collaborate with other people
  - GitHub
- First repo to contribute
  - [First Contributions](https://github.com/firstcontributions/first-contributions)
  - [Contribute to this Project](https://github.com/Syknapse/Contribute-To-This-Project)
- Next Step
  - Report Issue
  - Send PR
  - Start your own repo

The git basic and collabrate part can have more subtopics, and the "first repo to contribute" are some repo I personally find good for beginners.
Any suggestion is welcomed!

**Comment by ascodeasice** [comment]
Yes, I think those things can be added.
However, I don't think I'm experienced enough to add topics for them.
Anyone can suggest what should be added for these topics by comments

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by artchiee** [comment]
Hi all,

I've been watching this issue for any new updates, since Im interested in open source and I myself contributer. 

I would like to still develop a Roadmap for this thread! If the original poster still wants to continue at this! @ me and let's Resume with it.  
 Thank you!!
