### ISSUE TITLE
Add a language to CS roadmap

### ISSUE THREAD

**Issue by asyncci** [kamranahmedse/developer-roadmap#4436]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

```zig``` I guess is great language for cs , even so it is not 1.0.0 yet
https://ziglang.org/

**Comment by Polidoro-root** [comment]
It will be good if we had [Zig Language](https://ziglang.org/) roadmap itself, also showing intersections with C concepts and paths.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
