### ISSUE TITLE
Question About R Language, AzureML, and Hadoop in AI and Data Science Roadmap

### ISSUE THREAD

**Issue by navyabijoy** [kamranahmedse/developer-roadmap#4440]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Hello, I'm a student, and I greatly appreciate your AI and Data Science roadmap. I have a question regarding the necessity of R language in a data scientist's toolkit, as well as the relevance of databases such as AzureML or Hadoop in this field. I'm curious about why they haven't been included in the roadmap. Are these tools no longer considered relevant in the field of AI and Data Science?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
