### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by Hotbones** [kamranahmedse/developer-roadmap#4454]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

Hi guys, first I want to thank you for the excellent and always updated road map.
I am writing to add:
BDD ("Behavior-Driven Development") which is a methodology that is concerned with building the right functionality from the user's perspective and encourages communication and collaboration between team members. Some of the popular BDD tools include Cucumber, SpecFlow, Behave and JBehave, which help implement BDD principles in software development projects. And its key concepts in the roadmap.
Thank you very much 😎😺
Mr. Bones.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
