### ISSUE TITLE
Change Google Cloud Container Registry to Artifact Registry

### ISSUE THREAD

**Issue by digitalghost-dev** [kamranahmedse/developer-roadmap#4456]
### Roadmap URL

https://roadmap.sh/docker

### Suggestions

Google Cloud has since moved on to using [Artifact Registry](https://cloud.google.com/artifact-registry/). The section under the Docker roadmap > Container Registries > Others should be updated to talk about Artifact Registry.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
