### ISSUE TITLE
Add AI and DS roadmap to related roadmaps

### ISSUE THREAD

**Issue by Vedabahu** [kamranahmedse/developer-roadmap#4464]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Please add [AI and Data Scientist Roadmap](https://roadmap.sh/ai-data-scientist) to the `Related Roadmaps` in the {Python Roadmap}(https://roadmap.sh/python)

![roadmap sh_python](https://github.com/kamranahmedse/developer-roadmap/assets/79869936/1268f782-9517-45c5-8bab-b5badf394b8d)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
