### ISSUE TITLE
New Javascript Package Manager Update In Frontend Development Roadmap

### ISSUE THREAD

**Issue by iammihirsig** [kamranahmedse/developer-roadmap#4467]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

- New Package Manager Is Introduced  Recently Which Is Very Fast & Stable Called "[BUN](https://bun.sh/)".
- Adding That With Resources Under Package Managers Might Be Helpful For New Learners.

**Comment by iammihirsig** [comment]
Unable to merge at this time, I guess.

**Comment by iammihirsig** [comment]
Unable to merge at this time, I guess.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
