### ISSUE TITLE
ASP.NET Core Recommended Mocking library review

### ISSUE THREAD

**Issue by EddyHaigh** [kamranahmedse/developer-roadmap#4476]
### Roadmap URL

https://roadmap.sh/aspnet-core

### Suggestions

Currently, just Moq is recommended, but after recent issues, it [has become untrustworthy](https://www.reddit.com/r/dotnet/comments/15ljdcc/does_moq_in_its_latest_version_extract_and_send/). It may be worth recommending a different mocking framework or just not having a specific recommendation at all.

**Comment by julesrx** [comment]
[NSubstitute](https://github.com/nsubstitute/NSubstitute) and [FakeItEasy](https://github.com/FakeItEasy/FakeItEasy) are both pretty good options.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
