### ISSUE TITLE
[Vue Roadmap] Add Vue Query to API Calls item

### ISSUE THREAD

**Issue by joaopslins** [kamranahmedse/developer-roadmap#4477]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

Add https://tanstack.com/query/v4/docs/vue/overview to API calls item in the Vue roadmap.

For server side state management, Pinia is not really ideal, and implementing cache with axios by yourself might be very complex. So a library that implements that management is recommended.

AFAIK Vue Query seems to be the most used library for that purpose, and I think it would be a nice addition to the Vue roadmap.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
