### ISSUE TITLE
suggest for adding a eBook

### ISSUE THREAD

**Issue by m-alqblawi** [kamranahmedse/developer-roadmap#4479]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

you can add this eBook in the deep learning section.
where it is balanced in combining mathematics and code.

https://d2l.ai/

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
