### ISSUE TITLE
Notes - to highlight concept

### ISSUE THREAD

**Issue by Ramana5564** [kamranahmedse/developer-roadmap#4483]
### Feature Description

add notes feature, so that we can highlight that important concept by topic , it will be easy when we want to revise. Anyway thanks for this website!!!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
