### ISSUE TITLE
Extend a few more learning stages such as Database and Navigation (Routing)

### ISSUE THREAD

**Issue by michaelchiew08** [kamranahmedse/developer-roadmap#4487]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

As per title suggested.

Extend a few more learning stages with packages suggestion such as, 
Local database - example drift, hive, etc
Navigation (Routing) - example go_router, auto_route, beamer, etc

Not to enforce but just suggestion for future improvement and future learners.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
