### ISSUE TITLE
Topic Content

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#4490]
### Roadmap URL

roadmap.sh/spring-boot

### Suggestions

I just started using roadmap for learning java, MySQL and spring boot i am enjoying the website very much. However whenever i want to read in depth about a certain topic I have to use external website which sometimes work :) but it becomes draining jumpiing from site to site looking for something or information that could've been found in one.

Is it possible for you to start creating notes, not only the introductions but information about topic on the roadmap.sh in depth?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
