### ISSUE TITLE
Boa tarde,eu sugiro uma versão alternativa visando a acessibilidade para pessoas com tdah

### ISSUE THREAD

**Issue by BEFEFG** [kamranahmedse/developer-roadmap#4493]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Vocês deveriam fazer roadmaps adaptados para pessoas anomalias cerebrais,como ansiedade ou tdah,um roadmap que encaixe na agenda de uma dessas pessoas

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
