### ISSUE TITLE
Programming Lanugage

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [kamranahmedse/developer-roadmap#4498]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

As a DevOps Engineer roadmap in 'learn programming language' part C, C++ these both programming languages should be added because they are low level language as compare other OOPs based languages. C and C++ executes faster than other programming languages. So, system development and hardware development would be more flexible and ease.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
