### ISSUE TITLE
Resource Problem 

### ISSUE THREAD

**Issue by Predator792002** [kamranahmedse/developer-roadmap#4504]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Most of the Coursera resources are paid and it is too costly for some people it will be beneficial to add free or some YouTube resources as well

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
