### ISSUE TITLE
Backend Developer Roadmap AutoFac -> Autofac typo

### ISSUE THREAD

**Issue by doki050** [kamranahmedse/developer-roadmap#4511]
### Roadmap URL

https://roadmap.sh/aspnet-core

### Suggestions

Minor possible typo: 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/75539979/d2b8a91a-7fc8-45f2-96b6-bf7116b9a083)

Could be: Autofac, instead of AutoFac

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
