### ISSUE TITLE
Option to create a sub-roadmap

### ISSUE THREAD

**Issue by ddavis-palantir** [kamranahmedse/developer-roadmap#4512]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

It would be amazing if a user could hide sections from the road map, in order to create a sub-roadmap that could be shared with other users. A use case would be a mentor teaching a younger developer some things, and wanting only a couple stops on the roadmap to present to the person learning.

Maybe for some reason I want to hide the authentication and web components sections, to keep the map simple. 

Or I want to share only a section, so I hide everything except for the build tools and testing sections. 

Users could hit a button to restore the full roadmap. The sub-roadmap could be shared with a link that would hide the same sections as the original.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
