### ISSUE TITLE
Replace NPM with Yarn as recommended

### ISSUE THREAD

**Issue by DylanLee0918** [kamranahmedse/developer-roadmap#4513]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

I am kindly requesting to change the recommended package managers to **yarn**.

**Comment by julesrx** [comment]
I don't think there should be any recommended options for package managers. They all do somewhat the same things now, some more efficently than other, with a few variations on dependency resoltion and disk usage.
It's really a matter of personnal/company preference.

**Comment by DylanLee0918** [comment]
@julesrx yeah you are right, it is just that I highly suggested to use yarn for package managers. I know some will preferred to use yarn rather than npm.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
