### ISSUE TITLE
Adding notes

### ISSUE THREAD

**Issue by kylerasinger** [kamranahmedse/developer-roadmap#4515]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

I'd love to be able to add my own notes on the roadmaps to clarify ideas and give me a better reason to come back to roadmap while doing development.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
