### ISSUE TITLE
Label color

### ISSUE THREAD

**Issue by vincentferraro** [kamranahmedse/developer-roadmap#4518]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Hello, 

I have a suggestion, is it possible to change the label color when a topic is studied, instead have the label in grey and the word crossed, remplace by a green label in order to have a better view of our progression?

<img width="604" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/75814939/ee9a7394-a792-4389-a767-6c6b32e1f2c8">

Thank you

**Comment by Zhangjq-K** [comment]
Good idea

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
