### ISSUE TITLE
It's TailwindCSS not Tailwind

### ISSUE THREAD

**Issue by miguelgargallo** [kamranahmedse/developer-roadmap#4526]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

It's TailwindCSS not Tailwind

**Comment by avigdorsky** [comment]
Add copi laud

**Comment by miguelgargallo** [comment]
Solved here: https://github.com/kamranahmedse/developer-roadmap/pull/4529

**Comment by miguelgargallo** [comment]
(Close when merge)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
