### ISSUE TITLE
Add node: Polygon zkEVM under L2 Blockchains

### ISSUE THREAD

**Issue by oceans404** [kamranahmedse/developer-roadmap#4536]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

L2 Blockchains > Polygon zkEVM [content lives here](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/103-l2-blockchains/polygon-zkevm.md) and should be added as a node titled "Polygon zkEVM" within the L2 Blockchains section of the Blockchain roadmap

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
