### ISSUE TITLE
Data structures topic is very difficult

### ISSUE THREAD

**Issue by serverwind** [kamranahmedse/developer-roadmap#4539]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Before learning if...else statement, functions, classes Roadmap suggest to learn this:

- Introduction to the Stack Data Structure
- Introduction to the Queue Data Structure
- Intro to Recursion: Anatomy of a Recursive Solution 
- Binary Tree Algorithms for Technical Interviews - Full Course 
- Graph Algorithms for Technical Interviews - Full Course 
- Dynamic Programming - Learn to Solve Algorithmic Problems & Coding Challenges

And Data structures thread marked as "**beginner topic"**. This is pretty strange, and should be mistake.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
