### ISSUE TITLE
Full Stack RoadMap - Angular

### ISSUE THREAD

**Issue by KnightRag** [kamranahmedse/developer-roadmap#4545]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

Can we please add other UI libraries / framework? Like Angular, VueJs

**Comment by mughalmuneeb786** [comment]
These are frontend frameworks so its added on front-end roadmap.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
