### ISSUE TITLE
Additional Redis Resources in Backend Roadmap

### ISSUE THREAD

**Issue by AbdelrahmanSadat** [kamranahmedse/developer-roadmap#4548]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

I found this really helpful Redis crash course, it's perfect for an introduction, and it touches on other concepts in the roadmap like different DB types, microservices, & Kubernetes.

[The crash course](https://www.youtube.com/watch?v=OqCK95AS-YE)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
