### ISSUE TITLE
Can you create the C/embedded C Roadmap as  C++? 

### ISSUE THREAD

**Issue by doctor1cong** [kamranahmedse/developer-roadmap#4560]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

As the title ,I am a embedded C developer so i wish somebody can create the C roadmap~ Thanks all !

**Comment by H4rk0v** [comment]
That would be a great idea.

**Comment by yoohhal** [comment]
I need it too!!!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
