### ISSUE TITLE
Adding Link to Git 

### ISSUE THREAD

**Issue by Yogesh0808** [kamranahmedse/developer-roadmap#4561]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

In the Backend Roadmap:
## Resource Section for Git 
Requesting to add a Link from Microsoft learn
Here is the Link
https://learn.microsoft.com/en-us/training/modules/intro-to-git/ 
:)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
