### ISSUE TITLE
Notes feature 

### ISSUE THREAD

**Issue by Ajithwk** [kamranahmedse/developer-roadmap#4566]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

having a notes feature for each topic  can help us keep track of subtopics that we are learning, and also it can help us remember where we left and what all we learned.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
