### ISSUE TITLE
Add Move programming language for blockchain smart-contract language

### ISSUE THREAD

**Issue by procodeninja33** [kamranahmedse/developer-roadmap#4571]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

In the current version of the blockchain, the **Move programming language** is not included. Recently, Move programming language has gained popularity in the market due to its significant utility in blockchain development. Prominent chains like Aptos and Sui are among the most popular platforms that have adopted the Move programming language.

Some useful documentation links:
Move Language in formations written by MystenLab/Sui | https://github.com/MystenLabs/awesome-move
-- | --
Move Book (single source of knowledge about Move language) | https://move-book.com/
Move Language Uses | https://move-language.github.io/move/

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
