### ISSUE TITLE
Game Hacking

### ISSUE THREAD

**Issue by Nickyesulol** [kamranahmedse/developer-roadmap#4573]
### Feature Description

It would be really cool to add a game hacking roadmap which gives a lot of resources and explains all kinds of cheats and reverse engineering (maybe a separate roadmap which is connected to game hacking). There is like the classical internal and external cheats, but also the more exotic ones, for example where you rebuild your own "modified version" of the game, e.g: Minecraft clients. Also would be cool to include how kernel drivers work/anticheats and the concepts of bypassing them, bypassing DSE, etc. I am requesting this, because I am in no way eligible to provide any resources because I am still learning myself and that's why I am asking for this :D

**Comment by Grenish** [comment]
@Nickyesulol If gaming hacking is valid, then you can create your own Roadmap using AI. They have already given the option to do so.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
