### ISSUE TITLE
add Rust programming language to architect roadmap

### ISSUE THREAD

**Issue by wieerwill** [kamranahmedse/developer-roadmap#4577]
### Roadmap URL

https://roadmap.sh/software-architect

### Suggestions

The Rust language is ever evolving and gaining more developers and users over the last years. It would be nice to have it next to Java, Go and the other programming languages on the roadmap. 
Especially in context of embedded and reliable software development, this language is (currently) outstanding.

Next to a description and further links a brief description of the general Rust concepts would be helpful.

- [Main Website](https://www.rust-lang.org/)
- [The standard library](https://doc.rust-lang.org/std/index.html) Comprehensive guide to the Rust standard library APIs.
- [Edition Guide](https://doc.rust-lang.org/edition-guide/index.html) Guide to the Rust editions.
- [Rust by Example](https://doc.rust-lang.org/rust-by-example/) collection of runnable examples that illustrate various Rust concepts
- [Rust Playground](https://play.rust-lang.org/) to test your knowledge 

Definition of Ready:
- evaluate what to tell about rust in the roadmap
- define details of the definition of done

Definition of Done:
- short description of Rust programming language 
- general Rust concepts (borrowing/mutating values, crates, std lib)
- further links to dive deeper (like those above)
- add Rust to architect roadmap -> programming languages

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
