### ISSUE TITLE
Java Developer Roadmap

### ISSUE THREAD

**Issue by heim404** [kamranahmedse/developer-roadmap#4578]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

Switch "Data Structures" and "OOP, Interfaces, Classes" because for people o dont know, doest make sense learn diferent ways to store data when you dont know what is a class or a interface. Makes the learning course easier if people go for the fundamentals and then left to the right.

**Comment by AmineAouragh** [comment]
Hey @heim404 good idea for an issue 

I suggest that you change the issue title from 'Java Developer Roadmap' into 'Switch Data Structures and OOP, interfaces, classes in Java Roadmap' for it to be much more straightforward and clear.

If this isn't assigned to anybody and if it's okay if i work on it, i can try to take care of it.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
