### ISSUE TITLE
where to learn the coding

### ISSUE THREAD

**Issue by Simbadeveloper** [kamranahmedse/developer-roadmap#458]
was thinking also you could add link or online places where someone can learning coding

**Comment by dardanth** [comment]
Personally I have started with FreeCodeCamp.com, and I have managed to finish all challenges and I stopped to basic scripting algorithms where I'll get back after I finish some small tutorial projects.
I wanted to learn more and differently the JavaScript so I started with CodeCademy.com and they do a great job with JS basics elaboration. 
Other good options options are CodeSchool, Udacity and TreeHouse.com. What I am doing is combining FCC with codecademy because it's a great combo in the beginning. 

Just start somewhere and track your consistency, even if you do one challenge per day. 

Good luck Simba.

**Comment by Simbadeveloper** [comment]
@dardanth  thanks a lot will do just that
great for finishing all the challenge at FreeCodeCamp.com good encourage friend.

**Comment by luctst** [comment]
Also add Udemy could be good too :)

**Comment by Simbadeveloper** [comment]
@luctst you can be a teacher after learning at Udemy, passing the information to others too

**Comment by dalihari** [comment]
Odin project is a good source also

**Comment by kamranahmedse** [comment]
These will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. Thank you 🙏
