### ISSUE TITLE
Add images to the description of each section in the roadmap

### ISSUE THREAD

**Issue by hiep98** [kamranahmedse/developer-roadmap#4581]
### Feature Description

For example, in the Service Mesh details section of the developer roadmap there is only a text description like: "Service Mesh, like the Istio open source project, is a way to control how parts different applications share data with each other".
We can add images to the description of some other tasks like this "service mesh" task.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
