### ISSUE TITLE
Custom roadmap base on origin roadmaps of roadmap.sh

### ISSUE THREAD

**Issue by hiep98** [kamranahmedse/developer-roadmap#4582]
### Feature Description

Currently, the roadmap editor can only create a completely new roadmap. I hope the roadmap editor can have using roadmap templates available from roadmap.sh to update new entries into the roadmaps according to personal preferences.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
