### ISSUE TITLE
Checkbox items under learning box

### ISSUE THREAD

**Issue by TagFri** [kamranahmedse/developer-roadmap#4586]
### Feature Description

Having the links in the learning box being checkboxes for later references. So you could go back to 'Forms and validation' and do things you havn't done before at a later point

Meaning these:
<img width="1178" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/115897998/cfa74e44-b1a7-44ea-b58f-35913faa774b">

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
