### ISSUE TITLE
Projects/Checkpoints for DevOps

### ISSUE THREAD

**Issue by Garrowni** [kamranahmedse/developer-roadmap#4591]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

I was looking through the full stack guide and saw they have project ideas and suggestions. Would this be something that can be added to the DevOps Road Map? I think the checkpoints and project ideas would be extremely useful!

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
