### ISSUE TITLE
Download as markdown possible?

### ISSUE THREAD

**Issue by andyjessop** [kamranahmedse/developer-roadmap#4596]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

It would be amazing to be able to download these as markdown instead of as pdfs.

**Comment by AmineAouragh** [comment]
good suggestion

maybe we can have both options: download as pdf AND download as markdown? 

But what makes markdown more interesting compared to pdf format?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
