### ISSUE TITLE
AppSec Roadmap

### ISSUE THREAD

**Issue by cassiodeveloper** [kamranahmedse/developer-roadmap#4602]
### What is the title of the roadmap you are submitting?

Roadmap to learn Application Security

### Roadmap Link

https://roadmap.sh/r?id=652ff772f43a58c923e73944

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
