### ISSUE TITLE
General Knowledge

### ISSUE THREAD

**Issue by fabriciop-carvalho** [kamranahmedse/developer-roadmap#4605]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

I would like to have a section about general knowledge like we had in the previous version of roadmap.sh.
As a beginner, this section is great for learning in depth about the area and also having a more solid foundation of studies.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
