### ISSUE TITLE
This is addition we can do in JavaScript Roadmap 

### ISSUE THREAD

**Issue by Aditya2002rindhe** [kamranahmedse/developer-roadmap#5050]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

            I came across the Hoisting part in JavaScript. Just an improvement we can do is to add Variables hoisting and Functions hoisting differently with an example.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
