### ISSUE TITLE
Add WaitGroups to Go's roadmap (Going Deeper)

### ISSUE THREAD

**Issue by AhmadMadi** [kamranahmedse/developer-roadmap#5053]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions
Due to a request [issue 5039](https://github.com/kamranahmedse/developer-roadmap/issues/5039), I am suggesting to add WaitGroups as it covers a kind of concurrency in Go-lang. I have already made the changes, [here](https://github.com/kamranahmedse/developer-roadmap/pull/5042).

### Participation
- [x] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
