### ISSUE TITLE
Changes in Full Stack Developer Roadmap according to market

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#5063]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

According to the demand in market, we should add TypeScript after JavaScript in Frontend part and in the Backend part, replacing Postgres with MongoDB would go better with making the person go into MERN/MEAN/MEVN stack and many more other popular stacks.

**Comment by Paras-Baweja** [comment]
Resolved in pull #5069

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
