### ISSUE TITLE
Add others basics topics in the Python Roadmap

### ISSUE THREAD

**Issue by LuisanaMTDev** [kamranahmedse/developer-roadmap#5070]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

I think that Strings Formatting and File handling topics should be added in the Python Roadmap.

**Comment by Zomgitsluke** [comment]
For "learn the basics" I think "assignments" should be added as well and it's own thread

**Comment by LuisanaMT2005** [comment]
> For "learn the basics" I think "assignments" should be added as well and it's own thread

Yes, I think that could be a thread only for "operators" (there are many types of them)

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
