### ISSUE TITLE
Monitoring Open Source Tool CheckMK

### ISSUE THREAD

**Issue by atal-ab** [kamranahmedse/developer-roadmap#5073]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Infrastructure Monitoring
This CheckMK Montoring Open Source Tool is a great option to use in an organization. I recommand to add it to the DevOps/Infrastructure Monitoring RoadMap. i use the tool and has a lot free and Paid tools to be used.

Website of CheckMK: https://docs.checkmk.com/latest/en/

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
