### ISSUE TITLE
Mark for "Saved"

### ISSUE THREAD

**Issue by 77EnderGuy77** [kamranahmedse/developer-roadmap#5080]
### Feature Description

Make a new type for status that will be for Save. When you choose "Save" the small star will be showen on left/right. 
Example with cpp: Lambda ⭐. And in Profile can be shown new tab called "Saved" with in it will be shown like this "cpp/Lambda"

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
