### ISSUE TITLE
Change the Skipped and Done node colors

### ISSUE THREAD

**Issue by JasonAlvarado** [kamranahmedse/developer-roadmap#5081]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

I suggest changing the colors or opacity of the roadmap nodes to better differentiate which nodes are of interest from those that are not.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
