### ISSUE TITLE
Include Go Class by Matt in Backend roadmap

### ISSUE THREAD

**Issue by murrrda** [kamranahmedse/developer-roadmap#5082]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

![image](https://github.com/kamranahmedse/developer-roadmap/assets/148696561/53abded2-b224-45ff-b591-f997723f0961)
Please introduce [Go Class by Matt](https://www.youtube.com/playlist?list=PLoILbKo9rG3skRCj37Kn5Zj803hhiuRK6) in Back-end roadmap under Learn language - Go section. It is such a great and underrated resource

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
