### ISSUE TITLE
add pointers and stack/heap memory to the roadmap of golang

### ISSUE THREAD

**Issue by shayansm2** [kamranahmedse/developer-roadmap#5093]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions

I think pointers play a crucial role in go lang development. Therefore there should be a place explaining stack and heap memory and how pointers work in golang.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
