### ISSUE TITLE
Common runtimes are listed in wrong order of their complexity in CS roadmap

### ISSUE THREAD

**Issue by GeorgyYakunin** [kamranahmedse/developer-roadmap#5094]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

Polynomial complexity stay last in list although it is smaller than Exponential and Factorial. In roadmap is written there are listed in ascending order of their complexity.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
