### ISSUE TITLE
Change Javascript roadmap to Node.js roadmap

### ISSUE THREAD

**Issue by AhmedElaguab** [kamranahmedse/developer-roadmap#5098]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Hi,
In the Learn a Language part of Backend Roadmap, you've used Javascript Roadmap as a language while it should be Node.js Roadmap.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
