### ISSUE TITLE
Vue CLI is in Maintenance Mode

### ISSUE THREAD

**Issue by omar-the-junior** [kamranahmedse/developer-roadmap#5103]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

I suggest changing the first fundamental topic [vue CLI](https://cli.vuejs.org/guide/) to [create-vue](https://github.com/vuejs/create-vue) as the `vue CLI` is now in maintenance mode. Also the maintainers of vue cli recommended switching to `create-vue`

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
