### ISSUE TITLE
Add a Take Note Feature

### ISSUE THREAD

**Issue by njolipatrick** [kamranahmedse/developer-roadmap#5106]
### Feature Description

This will be helpful for each of the roadmap to help someone like me curate my thought and as I check out items to in-progress, done or even why i am skiping.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
