### ISSUE TITLE
Adding an checking option in the subtopics

### ISSUE THREAD

**Issue by RodrigoHenriqueDev** [kamranahmedse/developer-roadmap#5107]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

When you click in a topic, you can mark it as done, in progress and skip, and inside of a topic, you can see the subtopics inside it. It would be great if there would be check list to the user mark the specific subtopic as done.

I put the URL as Java, but it could be for any other roadmap.

**Comment by RodrigoHenriqueDev** [comment]
![image](https://github.com/kamranahmedse/developer-roadmap/assets/87452180/22d39d44-7a5d-43b3-91e8-4544ea19e66a)
A check button in "What are Data Structures?", "Data Structures and Algorithms" etc, could be implemented, so the user don't get lost every time they log in.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
