### ISSUE TITLE
Security(DevSecOps) and SQL

### ISSUE THREAD

**Issue by Nagendra9527** [kamranahmedse/developer-roadmap#5110]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Inclusion of code quality tools like Sonarqube and conatainer, package vulnerability scanning tools like snyk,trivy etc. DevOps Roadmap for better security of the application and also some basic database query knowledge is needed.

**Comment by ranjansmygit** [comment]
Security seems an integral component in DevOps, from supply chain security aspects. All security with shift left during the application lifecycle needs to be addressed.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
