### ISSUE TITLE
Add webhooks to the Real Time Section

### ISSUE THREAD

**Issue by svix-ken** [kamranahmedse/developer-roadmap#5290]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Should probably add webhooks to the real time section.

**Comment by abrahamthe1tec** [comment]
We all go through some tough times
Especially if u have a good heart in this cruel, sad world
We are so hollow and sad So much that people try to be bad to each other to
escape such feelings of emptiness and unwantedness
Everyone at some point in time tends to feel hollow and question their
existence which is often aggravated by loneliness.
At this point the best thing Is to get a hobby or an engaging job that u
really love doing or at least doesn't feel like a job,
Trust me you'll stop noticing all these things and you'll love spending
more and more time with yourself personally
That's how most people get over depression and learn to love themselves
Plus having a huge following or friends can be tiring at times too
Infact have many people in your life could weigh u down, because everything
u do is influenced by them, u wanna learn a new skill, they might think
it's not cool and you'll end up not doing that cause obviously it's not
"cool", infact you're always a joke or mockery away from ditching anything
u fancy deep down to be presentable and acceptable to them.
Most times you're not valued until you have something to offer, you don't
want to keep friends like that, some will even betray you, envy you, speak
ill of you behind Ur back, slander your name whenever it comes up and still
pretend to be your friend anytime they see you
So you see a lot of things could go badly by forcing things or friendship
or even being desperate for it
Hey read books, study even if it just for the love of it, and you know
what, you can study far more by getting an engaging action filled hobby
than sitting down to read a book about that activity, you still need to
read tho but you can see those theories and ideas come to life by
practicalising it or at least trying to
Most people are clueless about how we get most things done in a society
For example how do farmers produce these crops that we can't get enough of,
or how do all these Aquaculturists fell the fish market with various
cultured fishes, they didn't get such knowledge by sitting and doing
nothing, they learnt and they applied and they took note of what worked for
them and what didn't, obviously they went to school to get access to these
knowledge but these days internet and freelancing has made these things so
much better, you could literally pick your phone go on fiverr and look up
anyone who can teach you a particular skill you want to learn, and you'll
get it cheaper,save time and understand it better than paying for a
semester to learn that because of the approach to it, freelancers can do 2
things for you do the work for you, or teach you how to do the work
yourself.
You could do the work yourself or have the freelancer do the work for you
or could get a localised worker do the work for you while you oversea the
whole process, and I think u know by now which of them is more profitable.
Take it a step further, is your job making u sad all the time? Is it making
I feel like you're wasting your time? Does it feel like you have nothing to
look forward to? Like you're wasting away? sit down, think hard about how
to change this, come up with a plan, a plan to earn a good income and still
enjoy life, most of this rumination results in being self employed,
calculate the risks, don't just venture immediately into it full time, have
a trial period for this where you simply make it a pet project with minimal
investment, the purpose of this is to make mistakes and learn from it, to
work out your style or the approach best suited to achieving this
particular activity, experiment with it, there could already be a
conventional way to doing it, but you could discover a way to improve it,
even professionals do this, infact we cherish it cause that's how we
improve things, some one needs to think in the direction of "what if ?"
The trial period could last from a some month to a year but never let it
exceed a year, so you don't get sucked into that "I'm not ready yet fever",
this could vary from just a month to 1 yr depending on you chose
For example I chose fish culture at first I got a couple of fishes about
50, worked out their feed budget for a year, I realised I could afford
that, i looked into other amenities that they needed very importantly,
things like the aerator, plastic tanks, water pumps
I chose this because I had prior knowledge in it and because fishes don't
require much maintenance compared to poultry and livestock and it was a
consumable, basically I chose this because it seemed like the perfect
option for me at the time
I started rearing them and honestly compared to other types of start ups I
did excellently well, I got good stocks so they never got sick and I
changed waters everyday, I wasn't stuck at home just taking care of them, I
only feed them twice once in the morning and later in the evening when I
came back, although I must point out that I fed them more frequently when
they were very young, fishes are like humans when they're babies you don't
feed them much but u feed them frequently, when they're adults you could
even feed them once and they'll still grow and be fine, because they're
older now and they are not so vulnerable anymore, infact when they reach 3
months old, I hardly recorded mortality, they were so used to my lifestyle
thay they could tell ehem I woke up and when I came back, they are not dumb
just because they dont talk, they get wiser with age too,
So long story short I ended the trial period knowing what to do and what
not to do, things that helped them thrive and grow faster even when fed the
same quality and quantity of feed compared to bad practices, I was proud of
myself and I felt very accomplished all the while keeping this low-key,
even my family didnt know, I learnt so much about fish in general and
specific than I did in my first 3 yrs of college, thats the power of
practising or like some called it "doing".
Every time I spent with them I noticed things which led me to ask
questions, do little research and find answers, I already had the
literature from my college days, so I didn't need to spend on that, all i
had to do was read, and when I did i understood perfectly because it
related to my fishes in real time, it was no longer abstract, like for
example if it said check for any lesions or abrasion in the genital region
and I checked and I saw exactly that, applied the recommended treatments,
and saw improvement, do you think I'll ever forget that infection case or
the treatment to use? You see, That's the advantage practicals have over
theories, you remember more when you're doing something than when you're
just reading pages of pages of paper to pass an exam, as soon as that exam
is over, I always forget about it.
I get so involved with my pet project that I'm up late reading and trying
to visualise the next day activities and even at that I still wake up
energised and happy, you know how they tell you need 8 hrs of sleep to have
a productive and happy day, lies if u LOVE what u do, you can stay happy
and productive the next day with just 5 hrs of sleep, I'd go to work happy
not because of my work but because I'll get to chill with my fishes after
work and I'll perfect my craft,
I was happy because I know I won't be going to that same work everyday for
the rest of my life, I was happy because my plan to escape from this sad
work life was shaping up little by little
I cut my expenses massively cause now I had something to save up for
Something extremely important to me, you'd be surprised the things you can
overlook if you're passionate about something else, I didn't buy things for
my self unless it was extremely important and necessary, and more
importantly amidst all these I was very happy tbh I felt like I was in
control for the first time in my life and what's more I was doing it all
alone,
I used to have plenty of friends when I was younger until I got betrayed by
some and I looked into the rest closely only to realise the others had the
same potential to do just that to me, not too say I didn't have true good
friends but that scared me so much I lost how to be friends properly with
them, cause I cut out people from my life, the only ones I talked with
constantly was my family, and a few friends I could trust with my life even
them I couldn't be as transparent with them as i used to.
I set out to navigate life completely on my own, resolving that I must be
there for myself no matter what, I taught myself to be strong cause no one
cares although this is not true I believed it and TBH that was what helped
me to step up and plan for my life by my own self.
I felt like I was young and naive and that was why I was vulnerable to
wicked souls who took advantage of my naievity, optimism and good heart.
I determined to change those who had access to me, because i realised good
people get hurt the most and I wasn't ready to be a bad person
I still wanted to be kind and gentle and open minded but I was going to
limit those who got such privilege
Second year I quit everything focused fully on the one thing that gave me
true joy
Gained so much in that production cycle I couldn't believe it
The following year I decided to integrate it with Aquaponics and started a
crustacean branch off,
Perfected that as well and looking forward optimistically, in the process
of all these I met some great people, infact I met those I now fondly refer
to as "my people". The truth is this, When u follow your dreams, those you
meet amidst doing that, are those meant for you, believe it or not
Those you meet on your path to success, will most guaranteed be on their
way to their own success and you can just be the missing link to each other
success journey or story.
They'll rarely ever betray you, they don't even have such time and energy,
they're way too focused on their life and success to slander or organise
against you, they are never small-minded and they can see the bigger
picture just like you do.
This is what makes them your best chance at having friends or healthy
relationships.
You won't get this by trying to force people to like you or be Ur friend,
that's the easy way to mess Ur own life up
The point is this
You need to love the life that u lead in other to unfocus on what other
people are doing because most times, it's being bored or not having things
to look forward to doing that shifts our minds to thoughts like "where are
my friends?", "No one cares" "no one calls" etc
That type of train of thoughts leaves us bitter, depressed and hating life
But as soon we understand that we can survive perfectly on our own infact
we can thrive and be successful much better on our only then can we
transform this into a blessing we will always appreciate for the rest of
our lives
I've stopped looking down on myself and my confidence ever since I ventured
into fish farming.
I'm pretty much busy and occupied throughout my day and when I sleep I have
sweet dreams of imaginations crafted from the days experience
Now I don't have to work for any company, corporation or government, I get
payed handsomely well from my own farm, I manage myself and my business, I
am my own boss and I make all the decisions myself, i decide if i wanna
take a break if I'm not feeling too well, I decide when to go on a vacation
anytime i want to, i decide when to visit my parents, basically I enjoy
life much more now, plus its soo much fun, infact i think i overworked
myself in those early days, because i didn't hire any help but then It
never occurred to me because time flew by so fast which made me wish we had
way more than just 24hrs per day so I could do all the things I wanted to
do per day,
That's when I realised that you could be miserable literally minutes after
arriving at that job or life that u hate soo much, it's not that it's too
much work or too draining or too demanding, it's just that you hate doing
what you're doing and you feel like you're not in control of your life in
any way, it's thesame thing repeatedly
The only that I recommend to people who is sad about their situation is to
sit and think of how to change that situation for the better and most times
it's gonna lead to handling your business by yourself and not really
depending on anyone.
That is the only lasting cure that I can think of or recommend, when you
fix things on your own, it's really hard to be broken by anything anymore
cause now you're well equipped to deal with whatever life throws at you.
I used to hate having problems now I've realised that as long as you're
alive you're always gonna get them, they never go away, cause like energy
they can't be destroyed they only change form, mt problems 3 yrs back have
been solved and discarded but now i have new problems, which require new
solutions but I'm not sad or bitter about it cause deep down I know if I
think about the solutions hard enough and act on them I'll solve them.
So to anyone who wishes they were not lonely anymore, you might not know
what u have until u experience that life you wish for, not all that
glitters is gold
Now I enjoy my personal space more than anything else cause that's when I
can fully grow and become the best version of myself
You don't have a lover and because of that you're sad!, dude work on
yourself so much people would wish and pray that they get a chance to hang
with someone as awesome as you, plus there are countless people in
relationships wishing they were not, and if you don't believe me loook at
the rate of divorce and separation all around you, these people once came
on facebook to express how delighted, happy and in love they were, people
lie and its upto you to be wise and discern for yourself, i know some
people personally who get married to someone they dont love and still crave
for something outside their marital homes.
You may not understand why and I don't too or I don't care to know even but
people can be deceptive about everything and anything
I say it again Not all that glitters is gold, and your source of happiness
is more and more likely to come from within you, especially in this day and
age where powers that be make it harder every passing day to stay happy and
proud
I worked more but I was happy with it and enjoyed every second of it, that
was what made all the difference
why? Cause I genuinely loved every minute of it
It somehow bothers me when I come on Facebook and see soo many people
expressing their sadness at life and how much life sucks for them and how
much depressed they are all the time,
And I wonder all the energy people use in complaining and post about their
misery they could just channel that into doing something productive for
themselves, something they love, this is what the elites and powerful
people don't tell you, they can afford to go to therapies to hear this, but
most regular people can't afford that, which is why it seems like it is
only common among the destitute folks, when in reality you could do
something to change your situation and be happy
I wrote this after I made a post and shared to a group and unsurprisingly
it has the largest amount of engagement and likes by a long shot compared
to other I shared which goes to show that more people are going through
this than u can imagine,
So I decided to offer a bit of advice based on my own story and see if it
helps or inspires people affected

**Comment by kamranahmedse** [comment]
<img width="262" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/59124a25-3be6-48c1-98b4-5e433aa0925c">

This is already there

**Comment by svix-ken** [comment]
Sorry but I'm not seeing webhooks in the screenshot you provided.
