### ISSUE TITLE
Cannot link GPT API key to AI Roadmap Generator. 

### ISSUE THREAD

**Issue by tylervanable** [kamranahmedse/developer-roadmap#5345]
### What is the URL where the issue is happening

https://roadmap.sh/ai

### What browsers are you seeing the problem on?

N/A

### Describe the Bug

I copy and paste my GPT API key into roadmap.sh/ai. I press save. Roadmap.sh/ai tries to validate my key, but I am told to enter a valid OpenAI key. My OpenAI account (under OpenAI API Keys) displays a message that the API key was recently used, so I know it is a valid key.

### Output from browser console (if any)

"Please enter a valid OpenAI API key"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Akumine** [comment]
My suggestion is that this is due to the fact that you have a free version, while the roadmap uses gpt-4. But i`m not sure

**Comment by aliitascan** [comment]
@Akumine I'm having the same problem, although I'm using GPT Plus.

**Comment by berkaykrc** [comment]
same

**Comment by Ecruz69** [comment]
same , idk where the problem is , I'm using Chat GPT 4

**Comment by giabao-tran** [comment]
I'm having the same problem here

**Comment by dansholds** [comment]
Hey everyone!

I've just validated your issue and then got it working!

The issue here is the following...

- Access to GPT-4 is required.
- Having a paid Chat-GPT account (And therefore Chat-GPT access to GPT-4) **is not enough**.

To get GPT-4 **API access** you will need to:

- Login to https://platform.openai.com.
- Navigate to https://platform.openai.com/settings/organization/billing/overview (or similar).
- You will notice that if you've not been here before, it will say "Free Trial" and "$0.00" as the credit.
- Add a payment method and add $5 credit (the minimum).
- Create a new API key (I did, just to be sure).
- You will now be able to successfully add the key to roadmap.sh/ai 🎉.

If you look at my screenshot below you will see that I'm not on "Pay as you Go" and not "Free Trail" after adding payment details.

![Uploading Screenshot 2024-05-08 at 13.36.18.png…]()
<img width="499" alt="Screenshot 2024-05-08 at 13 29 55" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/1049e5e5-b1a2-4991-b013-52f6a842cff2">
