### ISSUE TITLE
Content Disappear When Creating Custom Version Of A Default Roadmap

### ISSUE THREAD

**Issue by ibraheemalayan** [kamranahmedse/developer-roadmap#5364]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Describe the Bug

When clicking the `Create your own version of this roadmap` button in any default roadmap, all the content and links inside the roadmap topics disappear.

<img width="1199" alt="Screenshot 2024-03-18 at 11 54 42" src="https://github.com/kamranahmedse/developer-roadmap/assets/35265448/76f082d6-dd20-4701-ab97-4c7ade99521d">

<img width="1255" alt="Screenshot 2024-03-18 at 11 55 00" src="https://github.com/kamranahmedse/developer-roadmap/assets/35265448/0b9b287e-dd5c-472f-bc07-acf5f075d49d">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ibraheemalayan** [comment]
Any update on this ?

**Comment by BrandSven** [comment]
If it is intended, it should be optional ("clear content on copy yes|no") in my opinion.

The reason we'd like to create a custom version from an existing map is to change details without having to build the whole content up from scratch. For us, "copy content: yes" would be the better (only) option.

**Comment by kamranahmedse** [comment]
@ibraheemalayan this is intended behavior. The reason is we have two different ways of making roadmaps - our official roadmaps are built manually with balsamiq and content is added through markdown files while the editor is all in database.

We are working on migrating the official roadmaps to use the editor as well. Once that is done, all the roadmaps will be editable and be able to let you fork the roadmaps as well.
