### ISSUE TITLE
help in choosing os

### ISSUE THREAD

**Issue by irajatkatal** [kamranahmedse/developer-roadmap#5574]
### Feature Description

As a beginner, many people don't know what OS they should choose to learn Linux. 
Could you make a list on the Linux roadmap based on the experience of what OS we should choose to start with Linux?

**Comment by dansholds** [comment]
Hi Rajat, we try to prevent bias towards different Operating Systems or technologies and the Linux Roadmap [https://roadmap.sh/linux] doesn't include any OS specific details intentionally.

If users want to engage in discussions around which OS is best suited for certain tasks then they can join those discussions in our Discord - https://discord.gg/n4VpVwPJ

As for what OS I would personally recommend to a beginner, I would recommend Ubuntu due to it's popularity and wide adoption.
