### ISSUE TITLE
why not includes the GraphQL?

### ISSUE THREAD

**Issue by xgqfrms** [kamranahmedse/developer-roadmap#562]
# why not includes the GraphQL?

> I think it will be the trending of new API development, just like GitHub version 4.

https://github.com/topics/github-api
https://developer.github.com/

**Comment by Firefishy** [comment]
In which chart? Frontend? Backend? DevOps?

**Comment by xgqfrms** [comment]
Frontend

**Comment by smoke** [comment]
It should be in backend as well.

**Comment by Bastorx** [comment]
Both side

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏

**Comment by acao** [comment]
I daresay that in Backend, GraphQL should be in "Learn about APIs" at this point, given the rate of adoption. REST should definately be learned always as a prerequesite to implementing GraphQL over HTTP, so the "learn at any time" legend key would remain, though GraphQL has a much broader scope and application than HTTP webservice APIs, all of it's applications would fall under the broad category of "APIs". 

Should I open a new ticket?  

that said, the place where it sits still makes sense, since it tends to be at the front of a "backend" stack (for example, to stitch service interfaces together into a common schema)
