### ISSUE TITLE
Access to `generateAIRoadmapFromText(string)`

### ISSUE THREAD

**Issue by JeremyMeissner** [kamranahmedse/developer-roadmap#5690]
### Detailed Description

Hello,

Why is the `/editor` part of the project closed-source? I wanted to understand how the `generateAIRoadmapFromText(string)` function works, but it’s in a private repository.

Can you explain why this part is not open-source? I believe sharing it (especially the prompting) could benefit the open-source community.

Thank you.

**Comment by dansholds** [comment]
Hey @JeremyMeissner!

In regards to `/editor`, we have a strict license in place to protect its integrity and the community that it ultimately serves. Sadly we have had instances where elements like `/editor` have been redistributed and used for profit through means like affiliate links or by promoting other poor-quality resources. 

We want to ensure that the project is used in ways that actually benefit developers rather than harming the community. However, if someone were to reach out with details of how they want to use the project, we are usually happy to grant permission for its use. This includes both personal use and within a company.

We are planning on running community events on our discord in the near future where we will do dives into the background of roadmap and other community points - https://discord.gg/YF8N7Dfb
