### ISSUE TITLE
Accessibility & Understandability - Color scheme

### ISSUE THREAD

**Issue by TheBox193** [kamranahmedse/developer-roadmap#574]
# Question
Would it make sense to pick a higher contrast, better Recommended / Possibilities / Meh color scheme?

As an experienced web dev, it wasn't immediate obvious which items were being recommended vs being an possibilities. Both the Yellow and Orange have a heavy / deep color. Even with a key, there is mental overhead parsing the meaning.

# My recommendation:
Recommend = Green
Possibilities = Grey
Meh = Very Soft Red

This will make the recommended route be more apparent. As green traditionally means 'good', 'grey' neutral, and 'red' bad. Think of a stoplight. Other colors could also be chosen that are more accessible.

# Rough Demo
![image](https://user-images.githubusercontent.com/220755/55660454-420a8f80-57bb-11e9-8fef-296fcae69ac2.png)

**Comment by Daniel-Yonkov** [comment]
I would prefer if the color of the additional descriptions could be changed from black and white font to something more in tune with the current color map.

**Comment by oryan** [comment]
Also, would be good to consider colorblind accessible colors. Green / Grey / Red might not be the best colors in that regard.

**Comment by lando-cal** [comment]
> 
> 
> Also, would be good to consider colorblind accessible colors. Green / Grey / Red might not be the best colors in that regard.

I searched this issue out for this very reason.
As a color blind individual, this was impossible for me to parse without utilizing the colorblind filters in Windows 10.

Some great info here either way, though!

**Comment by Ronkiro** [comment]
Just as an addition, i agree with all posts here, but i don't think the use of red here would be a great idea. For a roadmap that has non-experienced people, red at first look may sound as wrong...

Grey sounds nice for Meh IMO though. I think we could use Grey for the ones labeled as "meh", some (light) color for the possibilities and some (heavy) color for the other ones.

I think the problem is not the Yellow, but the orange. it also passes a heavy perspective...

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
