### ISSUE TITLE
The Course links are not working 

### ISSUE THREAD

**Issue by Aaron-p-saji** [kamranahmedse/developer-roadmap#5785]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

In the roadmap the course links are not working properly 

### Output from browser console (if any)

The link you clicked on is malformed. Contact the editor of the originating page.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@Aaron-p-saji can you be more descriptive with your issue please, I cannot replicate the issue on any of the course links in that roadmap.

It's possible that you're hitting issues with the coursera links due to an ad-blocker of some kind, can you confirm that it's only the coursera links you have issues with?

**Comment by Aaron-p-saji** [comment]
> @Aaron-p-saji can you be more descriptive with your issue please, I cannot replicate the issue on any of the course links in that roadmap.
> 
> It's possible that you're hitting issues with the coursera links due to an ad-blocker of some kind, can you confirm that it's only the coursera links you have issues with?

When i click on the course link the roadmap the redirect url provider pops an error saying the url doesn't exist
