### ISSUE TITLE
Prevent Auto-Closing of Node During Editing in Custom Roadmap

### ISSUE THREAD

**Issue by sohang3112** [kamranahmedse/developer-roadmap#5794]
### What is the URL where the issue is happening

https://draw.roadmap.sh/

### What browsers are you seeing the problem on?

Microsoft Edge

### Title:
Prevent Auto-Closing of Node During Editing in Custom Roadmap

### Description:
When editing a custom roadmap on roadmap.sh, the node being edited closes automatically if I switch to a different browser tab to consult information. This is frustrating because I have to reopen the node and it can result in loss of information. If I have added a title and a link but not yet added a description, the node discards its contents upon closing since it only saves when both title and description are present. This behavior is undesirable. The editing page should remain in the same state as it was before switching browser tabs.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
This is a pretty fair request, we will look into it and report back 👍 🦖

**Comment by dansholds** [comment]
For the time being this is intentional behaviour. The changes to topics save significantly faster than they previously did, now essentially rendering this none-issue (see screen recording below).

https://github.com/kamranahmedse/developer-roadmap/assets/25537601/0f2bbb59-b145-4c9a-bc38-f7e95ffe889d
