### ISSUE TITLE
Language Accessibility

### ISSUE THREAD

**Issue by JoaoDev01001** [kamranahmedse/developer-roadmap#5886]
### Feature Description

Hello, Devs!

I hope you're having a great day, evening, or afternoon.

As I've been reviewing your roadmap, it has helped me navigate the world of programming studies. As we all know, the democratization of the internet for everyone is very important, which is why sites like this exist!

As the title suggests, I'm writing to express a suggestion for improvement, which would be a website translated according to the user's region, or a native translation, not one provided by search engines, as they often distort the meaning and can ruin your good graphic work. Moreover, the idea of being able to download in PDF is very interesting; however, it comes in the standard language. Therefore, having this native support would be immensely incredible.

With all my cups of coffee,

Dev JoaoDev01001

**Comment by dansholds** [comment]
Hey @JoaoDev01001!

Thanks for such a pleasant and detailed message ☺️

We have localisation on our internal roadmap and we intend on working with people of different languages to manually translate each roadmap in order to be as accurate as possible! (Even Google translate isn't amazing!)

If you join our discord then you can keep up to date with our plans via our announcement channel and Community events! 

Thanks again! 🫂
