### ISSUE TITLE
More Deep Dive Resources

### ISSUE THREAD

**Issue by amritanupam** [kamranahmedse/developer-roadmap#6011]
### Feature Description

Please provide resources for a deeper insight into each individual topic, so that after learning the basics, one can learn more about the concept. Not required for all concepts though

**Comment by dansholds** [comment]
@amritanupam Can you specify which roadmap you're referring to?

**Comment by amritanupam** [comment]
Mostly Backend Roadmap & some of Dev-ops roadmap, since they have topics in common

**Comment by dansholds** [comment]
Our roadmaps are designed for beginners who go from zero knowledge to enough knowledge to confidently operate with the topic, the ceiling on "deeper insight" could potentially never be hit.

If you have specific things in mind then please let me know but we only cover up to certain points on purpose otherwise the journey of a single roadmap would be never ending.
