### ISSUE TITLE
Version management is missing

### ISSUE THREAD

**Issue by kvendingoldo** [kamranahmedse/developer-roadmap#6021]
### Roadmap URL

https://roadmap.sh/terraform

### Suggestions

Please, add section "version management" with the following options: tfenv, tenv, tfswitch

**Comment by dansholds** [comment]
@kvendingoldo version management/version switching in Terraform is not a native or mandatory feature of Terraform (although I used it many times in the past when adding new modules and resource files to an old Terraform project), hence why it isn't in here, feel free to submit a link to the [tfev](https://github.com/tfutils/tfenv) repo along with some copy to the provider > versioning subtopic or to another topic that suits it more.

Also since we're creating a roadmap for terraform beginners, I wouldn't advise people to create a terraform roadmap that contains multiple versions of Terraform.

**Comment by dansholds** [comment]
@kvendingoldo I'll look into it.

**Comment by dansholds** [comment]
@kvendingoldo I will look to add it as a sub-topic within "Scaling Terraform"

**Comment by kvendingoldo** [comment]
@dansholds I see new section "version management", but don't see tenv. tenv is a successor of tfenv. can you add it?
article about it: https://www.env0.com/blog/how-to-use-tenv-to-streamline-iac-version-management

**Comment by dansholds** [comment]
@kvendingoldo you can add it via a PR
