### ISSUE TITLE
Can't install renderer

### ISSUE THREAD

**Issue by david-slatinek** [kamranahmedse/developer-roadmap#6065]
### What is the URL where the issue is happening

roadmap.sh

### What browsers are you seeing the problem on?

Other

### Describe the Bug

When I try to install the renderer using `npm run generate-renderer`, I get the following error:
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@david-slatinek This is not a bug, this is a private repository. If this is causing you major issues then let us know, but since the only contributions that the community can make to the project are in the form content for topics & subtopics, this should not be an issue (I do not have access to this repo and make countless contributions to the project daily).
