### ISSUE TITLE
There is no "C / C++" language

### ISSUE THREAD

**Issue by Xeverous** [kamranahmedse/developer-roadmap#611]
The term is as much meaningful as "Java/JavaScript" or "Ham/Hamster" or "D/Delphi". Each of these is a different language and has different conventions.

There is some bias that C and C++ are somehow related and should be written as one term. They have as much in common as JavaScript and Java: just a part of the name, because one language was partially based on another.

Adding more from Stroustrup's FAQ:

> [...] people use "C/C++" as if it meant something specific and as if they knew what it meant, leading to much confusion and misery. People should ask "What is C/C++?" and then on reflection stop using the term. It does harm.
>
> There is no language called "C/C++". The phrase is usually used by people who don't have a clue about programming (e.g. HR personnel and poor managers). Alternatively, it's used by people who simple do not know C++ (and often not C either). When used by programmers, it typically indicates a "C++ is C with a few useful and a lot of useless complicated features added" attitude. Often, that is the point of view of people who like to write their own strings and hash tables with little knowledge of the standard library beyond printf and memcpy.

**Edit: I see this issue spawned a quite discussion. Just noting that the goal of this issue is to stop using "C/C++" term. Currently the Dev Ops chart uses this as 1 language.**

**Comment by neu-rah** [comment]
agree, modern C++ is fundamentally different from C in ways that "can not" be replaced by C. I'm talking about templates and meta-programming (programming the compiler)

**Comment by Ronkiro** [comment]
I think people consider this due not to C++ being replaced by C, but the opposite.

In my perspective, C++ can completely replace C with ease.

**Comment by neu-rah** [comment]
in principle any Turing complete language can replace any other.
from my experience, looking at C projects that i like the functionality, I see that I would like to rewrite the C code using modern C++, just because the conditional compilation usually expressed with macros on C side makes is huge, and type loose while in contrast modern C++ offers compiler side meta-programming (compiler side/time) that at least (for very good macros) makes the program much lighter to read/write/maintain and possibly more generic, reusable if not faster/smaller (compile time optimized), of course for non-trivial cases.
Its of course possible to hook C++ on top of C libraries, but it looses the advantage of compile time optimization/customization.
But I recognize that this might be a corner case.

**Comment by rainbyte** [comment]
Some people think that C++ is a superset of C, which is far from true, because some valid C programs do not are rejected when using a C++ compiler. Other languages like Objective-C are C supersets, which means that every C program is a valid Objective-C program.

**Comment by kamranahmedse** [comment]
I agree with the sentiment. C++ was basically the evolved version of C and that was the reason behind putting them both in the same block but yes, I need to fix that. This will be done in the 2020 release. Thank you 🙏
