### ISSUE TITLE
Roadmap for Linux Kernel Developer

### ISSUE THREAD

**Issue by onlinejudge95** [kamranahmedse/developer-roadmap#630]
The scope covers to much extent the end to end web development road-map. What do you think about a roadmap for **Linux Kernel Developer**?

**Comment by Goutam1511** [comment]
It would be great and really helpful for freshers like me who just started the path to becoming a Linux Kernel Developer.

**Comment by karthickraja-kamaraj** [comment]
Is there any basic informations available already?
I am hearding this for the first time. 😯

**Comment by kolanski** [comment]
https://bootlin.com/ i think we can gather base info from here

**Comment by onlinejudge95** [comment]
@karthickraja-kamaraj I think there are multiple resources, we might need to dig deep.
@kolanski good game dude, let's hope this catches traction.

**Comment by louwers** [comment]
Go to `#kernelnewbies` on OFTC.net IRC. And read this: https://lists.kernelnewbies.org/pipermail/kernelnewbies/2017-April/017765.html

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!

**Comment by haruzheng** [comment]
Hi all,

I think roadmap for Linux Kernel Developer is important. Because it is so complex, so i think it is must be exist. But i am a beginner of Linux Kernel Developer, so i not has enough knowledge for Linux Kernel.

I try to write a series of articles for Linux Kernel for beginner by traditional chinese. But i think maybe roadmap for Linux Kernel Developer exist is helpful.


Thank you
Haru

**Comment by navitux** [comment]
so... Is this issue closed but: Is that a work in progress or not ??

I'm in doubt

**Comment by belanasaikiran** [comment]
> so... Is this issue closed but: Is that a work in progress or not ??
> 
> I'm in doubt

me too
