### ISSUE TITLE
Let's create a roadmap for mobile developers ( iOS, Android )

### ISSUE THREAD

**Issue by jwyterlin** [kamranahmedse/developer-roadmap#64]

**Comment by k30v1n** [comment]
Very good suggestion

**Comment by collinschumba** [comment]
i too feel this way

**Comment by renanrider** [comment]
;)

**Comment by k30v1n** [comment]
I think this roadmap could pass through:

**Native development:**
- C# (Windows Phone)
- java (Android)
- Swift/Objective-C (IOs). Objective-C is important because a lot of companies still use it.

**Cross Platform Development**
- IONIC (Angular and Node js)
- Xamarin (C#)

In my country, Xamarin development is becoming a good option. A bunch of mobile development companies are asking for that.

Well, these options are what I know, but I don't know if @kamranahmedse will accept these modifications. Will you?

**Comment by m1ga** [comment]
@k30v1n since the Title of the Map is "Webdeveloper" it would be a better idea to create a custom map for mobile development. 

You can extend the "Cross Platform" path with:
* Native Frameworks
* Hybrid Frameworks

Then there are more frameworks inside these sections like:
* Appcelerator Titanium
* Phonegap/Cordova
* Nativescript
* ReactNative
and others

**Comment by k30v1n** [comment]
@m1ga Nice point! But I understand that that title is just in the README.md file. As the repository's name suggest, "developer-roadmap", can be any type of development. Maybe we can separate in folders inside the repository, like:
- WebDeveloper / FrontEndDeveloper
README.md (with the current Front End Path)

- DevOps
README.md (with the current DevOps Path)

- BackEndDeveloper
README.md (with the current BackEnd Path)

- MobileDeveloper
README.md (new one with Mobile path)

What do you think about it?

Nice suggest about the extension of "Cross Platform" and the others frameworks.

**Comment by kamranahmedse** [comment]
Feel free to create a PR if anyone is up for it. But the repository focuses on "web developer", so closing it for being irrelevant.

Thanks though.

**Comment by jlampa** [comment]
There already is one: https://github.com/godrm/mobile-developer-roadmap

**Comment by ElFryskai** [comment]
@jlampa Unfortunately no plan for Android and Hybrid roadmap

**Comment by anphan091092** [comment]
Very good suggestion
