### ISSUE TITLE
Project Idea: Real-Time messaging app

### ISSUE THREAD

**Issue by pyoneerC** [kamranahmedse/developer-roadmap#6618]
### What Roadmap is this project for?

Backend Roadmap

### Project Difficulty

Advanced

### Add Project Details

Build a real-time messaging app for web/mobiles and optionally you can send images, reactions, calls, etc.

**Comment by kamranahmedse** [comment]
Thank you for all the project ideas @pyoneerC.
Could you please add some more details to these ideas? Look at the [details we have in the existing project ideas](https://roadmap.sh/backend/projects).

**Comment by BeardedOwl1357** [comment]
Its a great idea. I have one resource for golang. See if this helps you to flesh out your idea more

https://www.youtube.com/watch?v=pKpKv9MKN-E

**Comment by pyoneerC** [comment]
Thank you guys. Do I just write a detailed issue ans you implement it or should I do a PR too?

**Comment by kamranahmedse** [comment]
@pyoneerC better to write the detailed text in the issue, since we will probably need to revisit some sections. You can follow the structure we have in other project ideas e.g. [this one](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/projects/todo-list-api.md) or [the format in these files](https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/projects).

**Comment by kamranahmedse** [comment]
Looking at it now and we already seem to have similar idea for a [Broadcast Server](https://roadmap.sh/projects/broadcast-server).
