### ISSUE TITLE
Build a program whilst utilising Git/GIthub

### ISSUE THREAD

**Issue by Jakub768** [kamranahmedse/developer-roadmap#6743]
### What Roadmap is this project for?

Git and Github

### Project Difficulty

Beginner

### Add Project Details

You are required to show your understanding of Git/Github by simply creating a repo (a program of any kind) and committing your code as you go. 

You can build any program as you like but it must utilise Git/Github stuff such as:
- Version control - committing changes with clear comments.
- Branch Management - create branch, commit to branch, Pull Request from branch to master...
- Github Issue management - Creating GH issues, reviewing issues and deleting completed issues.
- Github Pull Requests - Review and comment Pull Requests.
- Readme - Describe the purpose of your program and compilation process.

OPTIONAL:
- Github Actions - Look into automation and include it such as linting.
- Pull Request & GH issue templates - Create template for both PR and GH issues.
- Licensing - Choose a license deemed suitable for your program (Will users be able to take it or have a strict compliance?)

Sample idea:

- **Create a program that translates a set of words from English to another language.** - 
    - Create multiple github issues for bugs and feature that you may encounter. 
        - Thus, create branches for your bugs/features separately
    - Create a Readme that tells users what is your program about and how to contribute.
    - Any other actions you feel might be good from the list above.

This Git/Github exercise will sharpen your understanding of Version Control and Git/Github usage which will help you manage the repo and welcome anyone who would like to develop your projects in future.

**Comment by Jakub768** [comment]
@kenshanta Why the dislike? Could you explain what would you change? I am open for suggestions.

**Comment by kenshanta** [comment]
Having a roadmap for beginners on how to use Git/GitHub is redundant because there already are repos/projects who aim to teach newbies how to utilize git/GitHub. A good example would be the repos in  [first contributions](https://github.com/firstcontributions)


Going with your feature request will basically beat the concept of the roadmap since it's used as a guidance tool and not a starter pack.

Better wait for the maintainers to react since they have a better insight on the concept.

**Comment by dansholds** [comment]
Two points on this:

1. They're submitting a Project request not a roadmap request.

This project is redundant though as all projects created on Roadmap.sh are required to be hosted on GitHub in order to be verified, therefore every project achieves what this project set out to achieve.

2. We do actually have a GitHub roadmap @kenshanta - https://roadmap.sh/git-github

This roadmap was built with the help of the GitHub Education team as well as shared on their education newsletter and socials.
