### ISSUE TITLE
what program do you use to draw this diagrams?

### ISSUE THREAD

**Issue by mobop** [kamranahmedse/developer-roadmap#697]
?

**Comment by ribeirojose** [comment]
> Roadmaps are made using Balsamiq

from [here] (https://github.com/kamranahmedse/developer-roadmap/blob/ecd4839acf8013f432bef72a267bf83f3738f220/CONTRIBUTING.md)

**Comment by mobop** [comment]
That's a proprietary software

**Comment by mobop** [comment]
@kamranahmedse , what the hell is going on?

**Comment by nazarhussain** [comment]
@mobop Your question is replied earlier. Those diagrams are made in **[Balsamiq](https://balsamiq.com/wireframes/)**.

**Comment by mobop** [comment]
@nazarhussain , i know that. my question is why a proprietary software is used?

**Comment by nazarhussain** [comment]
That's a good question. I guess its just because of fo better UI/UX of the software and nice output that it generates. I also use Balsamiq a lot for couple of years, but now switched to something proprietary software. 

If you know any open source or freemium that have equivalent capabilities to generate such nice mind maps and graphs please suggest. I will try out for personal use as well will try to contribute with it.
