### ISSUE TITLE
C++ Logical operations mistake

### ISSUE THREAD

**Issue by McMad0077** [kamranahmedse/developer-roadmap#7376]
### Detailed Description

I noticed that in the C++ Logical Operations topic, the final code example was written as this;

int a = 5, b = -10, c = 15;

if (a > 0 && (b > 0 || c > 0)) {
    std::cout << "At least two values are positive." << std::endl;
}

This is supposed to check that at least 2 values are positive, but the way it is written, it will only check to see that int a and at least one other value is positive. So if I had set a to -1, and b and c to 1, the resaulting bool value in the if statement will be false.

I propose that the code be replaced with:

int a = 5, b = -10, c = 15;
bool x = a > 0, y = b > 0, z = c > 0;

if ((x && y) || (y && z) || (x && z)) {
    std::cout << "At least two values are positive." << std::endl;
}

I am not sure if i set the bool values correctly, but if they are set correctly, this would individually check all values aganst each other and insure that at least 2 values are greater than 0.

**Comment by McMad0077** [comment]
I would also like to add that in the C++ Logical operations topic does not include headers or functions when the other topics include headers and functions in the code examples

**Comment by AnantTudu** [comment]
Your revised code is an improvement over the original because it properly checks for any combination of two positive values, not just one specific combination involving a.
1st Code
int a = 5, b = -10, c = 15;

if (a > 0 && (b > 0 || c > 0)) {
std::cout << "At least two values are positive." << std::endl;
}

This code checks if a is positive and if either b or c is positive.
This would only work if a is always positive, so if a is negative but b and c are positive, the condition will incorrectly evaluate to false. It fails to check all combinations of two positive values. For example, if a = -1, b = 1, and c = 1, the result would be false, even though there are two positive values (b and c)


2nd Code
int a = 5, b = -10, c = 15;
bool x = a > 0, y = b > 0, z = c > 0;

if ((x && y) || (y && z) || (x && z)) {
std::cout << "At least two values are positive." << std::endl;
}

Here
 you’re first evaluating whether each individual value is positive and storing the results as boolean values (x, y, and z).
Then, you're checking for all possible combinations of two positive values:
(x && y) checks if a and b are positive.
(y && z) checks if b and c are positive.
(x && z) checks if a and c are positive.

This approach correctly identifies if any two values (regardless of which) are positive, ensuring that at least two positive numbers are present.

**Comment by dansholds** [comment]
Submit a PR to fix it!

**Comment by McMad0077** [comment]
> Submit a PR to fix it!

What is a PR?

**Comment by dansholds** [comment]
> > Submit a PR to fix it!
> 
> What is a PR?

A pull request.
