### ISSUE TITLE
There is a z-index bug in the submit solution section.

### ISSUE THREAD

**Issue by aligunesv** [kamranahmedse/developer-roadmap#7701]
### What is the URL where the issue is happening

https://roadmap.sh/projects/single-page-cv

### Describe the Bug

I think it is an error that can be corrected by just checking the z-index. It is not a big error but it can be taken care of.

![Ekran görüntüsü 2024-11-08 152711](https://github.com/user-attachments/assets/7ef543b7-f5e9-4aaf-9f3d-26e81c72ebcf)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Shivam-Katare** [comment]
Hey, @aligunesv can I work on this issue?

**Comment by kamranahmedse** [comment]
@Shivam-Katare go ahead

**Comment by Shivam-Katare** [comment]
Sure @kamranahmedse

**Comment by Shivam-Katare** [comment]
Hey @kamranahmedse, I am getting this error when I try to login/sign up or try to open this modal. The error message shows that, there is an API failure due to an incorrect endpoint URL. Is this issue related to an environment variable? Do I need to create any environment variables locally to resolve this? Let me know. Thanks. 

Without this, the `start and submit` project modal will not open up unless I hardcoded the modal value for testing. 

![image](https://github.com/user-attachments/assets/a86eb005-0d90-40b8-8d9f-6fb870dad162)

![image](https://github.com/user-attachments/assets/68699cdd-e327-492d-81e4-2192cd4de461)

**Comment by arikchakma** [comment]
@Shivam-Katare it's because of the API, you can try modifying the frontend API call. So that you can use that to debug.
