### ISSUE TITLE
Addition of BDD as a core practice

### ISSUE THREAD

**Issue by cliffbdf** [kamranahmedse/developer-roadmap#892]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

BDD should be listed as a core set of ideas/practices. It is a general approach to how automated tests can be written and maintained for all levels of testing (above the unit level) and all aspects of a system.

I would also suggest that TDD (which is about unit level tests) be removed, as it is not a core practice, but rather is a highly opinionated practice.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
